/* ============================================================
   IMPARA data pack — ~2000 most common Italian words +
   ~500 common phrases, organised by theme/situation.
   Nouns carry their article (gender). Verbs are infinitives.
   ============================================================ */
const WORD_THEMES = [
{cat:"Pronouns & people words", words:[
["io","I"],["tu","you"],["lui","he"],["lei","she"],["noi","we"],["voi","you (pl)"],["loro","they"],["me","me"],["te","you"],["mi","me / myself"],["ti","you / yourself"],["ci","us / ourselves"],["vi","you (pl)"],["si","oneself"],["lo","it / him"],["la","it / her"],["li","them (m)"],["le","them (f)"],["gli","to him / them"],["ne","of it / them"],["chi","who"],["che","that / which"],["cui","whom / which"],["questo","this"],["questa","this (f)"],["quello","that"],["quella","that (f)"],["questi","these"],["quelli","those"],["stesso","same / self"],["altro","other"],["altri","others"],["ognuno","everyone"],["qualcuno","someone"],["nessuno","no one"],["tutti","everybody"],["ciascuno","each one"],["uno","one"],["entrambi","both"],["alcuni","some"],["molti","many"],["pochi","few"],["tanti","so many"],["chiunque","anyone"],["mio","my / mine"],["tuo","your / yours"],["suo","his / her"],["nostro","our"],["vostro","your (pl)"],["proprio","one's own"]
]},
{cat:"Essential verbs I", words:[
["essere","to be"],["avere","to have"],["fare","to do / make"],["dire","to say"],["potere","to be able"],["volere","to want"],["dovere","to have to"],["sapere","to know"],["andare","to go"],["venire","to come"],["vedere","to see"],["dare","to give"],["stare","to stay / be"],["parlare","to speak"],["trovare","to find"],["sentire","to hear / feel"],["lasciare","to leave / let"],["prendere","to take"],["guardare","to watch / look"],["mettere","to put"],["pensare","to think"],["passare","to pass / spend"],["credere","to believe"],["tenere","to keep / hold"],["portare","to bring / carry"],["capire","to understand"],["chiedere","to ask"],["restare","to stay"],["diventare","to become"],["mandare","to send"],["aspettare","to wait"],["arrivare","to arrive"],["riuscire","to succeed / manage"],["entrare","to enter"],["uscire","to go out"],["chiamare","to call"],["finire","to finish"],["seguire","to follow"],["cominciare","to begin"],["vivere","to live"],["morire","to die"],["scrivere","to write"],["leggere","to read"],["correre","to run"],["aprire","to open"],["chiudere","to close"],["pagare","to pay"],["comprare","to buy"],["vendere","to sell"],["usare","to use"]
]},
{cat:"Essential verbs II", words:[
["lavorare","to work"],["studiare","to study"],["imparare","to learn"],["insegnare","to teach"],["giocare","to play"],["cantare","to sing"],["ballare","to dance"],["cucinare","to cook"],["mangiare","to eat"],["bere","to drink"],["dormire","to sleep"],["svegliarsi","to wake up"],["alzarsi","to get up"],["lavarsi","to wash oneself"],["vestirsi","to get dressed"],["sedersi","to sit down"],["camminare","to walk"],["viaggiare","to travel"],["guidare","to drive"],["volare","to fly"],["nuotare","to swim"],["saltare","to jump"],["cadere","to fall"],["sorridere","to smile"],["ridere","to laugh"],["piangere","to cry"],["amare","to love"],["odiare","to hate"],["baciare","to kiss"],["abbracciare","to hug"],["aiutare","to help"],["ringraziare","to thank"],["scusarsi","to apologize"],["promettere","to promise"],["dimenticare","to forget"],["ricordare","to remember"],["spiegare","to explain"],["rispondere","to answer"],["domandare","to ask"],["raccontare","to tell"],["mostrare","to show"],["spingere","to push"],["tirare","to pull"],["rompere","to break"],["costruire","to build"],["riparare","to repair"],["cambiare","to change"],["provare","to try"],["scegliere","to choose"],["decidere","to decide"]
]},
{cat:"Essential verbs III", words:[
["perdere","to lose"],["vincere","to win"],["giocare","to play"],["correggere","to correct"],["controllare","to check"],["cercare","to look for"],["incontrare","to meet"],["conoscere","to know (a person)"],["presentare","to introduce"],["invitare","to invite"],["accettare","to accept"],["rifiutare","to refuse"],["offrire","to offer"],["regalare","to give a gift"],["ricevere","to receive"],["accompagnare","to accompany"],["lasciare","to leave"],["tornare","to return"],["restare","to remain"],["muoversi","to move"],["fermarsi","to stop"],["continuare","to continue"],["smettere","to quit / stop"],["evitare","to avoid"],["preoccuparsi","to worry"],["arrabbiarsi","to get angry"],["divertirsi","to have fun"],["annoiarsi","to get bored"],["riposare","to rest"],["lavare","to wash"],["pulire","to clean"],["sporcare","to dirty"],["ordinare","to order / tidy"],["preparare","to prepare"],["servire","to serve / need"],["bastare","to be enough"],["piacere","to please / like"],["mancare","to miss / lack"],["succedere","to happen"],["sembrare","to seem"],["significare","to mean"],["dipendere","to depend"],["funzionare","to work (function)"],["dubitare","to doubt"],["sperare","to hope"],["immaginare","to imagine"],["sognare","to dream"],["svolgere","to carry out"],["riempire","to fill"],["svuotare","to empty"]
]},
{cat:"Adverbs & connectors", words:[
["e","and"],["o","or"],["ma","but"],["però","however"],["perché","because / why"],["quindi","so / therefore"],["allora","then / so"],["anche","also / too"],["pure","also"],["invece","instead"],["mentre","while"],["quando","when"],["dove","where"],["come","how / as"],["quanto","how much"],["se","if"],["non","not"],["mai","never"],["sempre","always"],["spesso","often"],["a volte","sometimes"],["raramente","rarely"],["già","already"],["ancora","still / yet"],["appena","just / as soon as"],["subito","right away"],["presto","soon / early"],["tardi","late"],["adesso","now"],["ora","now / hour"],["poi","then / after"],["prima","before / first"],["dopo","after"],["qui","here"],["qua","here"],["lì","there"],["là","there"],["sopra","above"],["sotto","below"],["dentro","inside"],["fuori","outside"],["davanti","in front"],["dietro","behind"],["vicino","near"],["lontano","far"],["insieme","together"],["solo","only / alone"],["forse","maybe"],["certo","of course"],["davvero","really"]
]},
{cat:"Prepositions & quantity", words:[
["di","of / from"],["a","to / at"],["da","from / by"],["in","in"],["con","with"],["su","on"],["per","for"],["tra","between / among"],["fra","between / among"],["senza","without"],["contro","against"],["verso","toward"],["dopo","after"],["durante","during"],["secondo","according to"],["fino a","until"],["oltre","beyond / besides"],["circa","about / around"],["attraverso","through"],["lungo","along"],["molto","much / very"],["poco","little"],["tanto","so much"],["troppo","too much"],["abbastanza","enough"],["più","more"],["meno","less"],["tutto","all / everything"],["niente","nothing"],["nulla","nothing"],["qualcosa","something"],["ogni","every"],["alcuni","some"],["parecchio","quite a lot"],["mezzo","half"],["doppio","double"],["paio","pair / couple"],["gruppo","group"],["parte","part"],["pezzo","piece"],["numero","number"],["quantità","quantity"],["totale","total"],["resto","rest / change"],["insieme","set / together"],["dozzina","dozen"],["centinaio","hundred (approx)"],["migliaio","thousand (approx)"],["punto","point"],["livello","level"]
]},
{cat:"Numbers", words:[
["zero","zero"],["uno","one"],["due","two"],["tre","three"],["quattro","four"],["cinque","five"],["sei","six"],["sette","seven"],["otto","eight"],["nove","nine"],["dieci","ten"],["undici","eleven"],["dodici","twelve"],["tredici","thirteen"],["quattordici","fourteen"],["quindici","fifteen"],["sedici","sixteen"],["diciassette","seventeen"],["diciotto","eighteen"],["diciannove","nineteen"],["venti","twenty"],["trenta","thirty"],["quaranta","forty"],["cinquanta","fifty"],["sessanta","sixty"],["settanta","seventy"],["ottanta","eighty"],["novanta","ninety"],["cento","one hundred"],["mille","one thousand"],["milione","million"],["miliardo","billion"],["primo","first"],["secondo","second"],["terzo","third"],["quarto","fourth"],["quinto","fifth"],["sesto","sixth"],["settimo","seventh"],["ottavo","eighth"],["nono","ninth"],["decimo","tenth"],["ultimo","last"],["coppia","pair"],["metà","half"],["terzo","a third"],["percento","percent"],["volta","time (occurrence)"],["doppio","double"],["singolo","single"]
]},
{cat:"Time & calendar", words:[
["il tempo","the time / weather"],["l'ora","the hour"],["il minuto","the minute"],["il secondo","the second"],["il giorno","the day"],["la settimana","the week"],["il mese","the month"],["l'anno","the year"],["il secolo","the century"],["oggi","today"],["domani","tomorrow"],["ieri","yesterday"],["dopodomani","the day after tomorrow"],["l'altroieri","the day before yesterday"],["la mattina","the morning"],["il pomeriggio","the afternoon"],["la sera","the evening"],["la notte","the night"],["mezzogiorno","midday"],["mezzanotte","midnight"],["lunedì","Monday"],["martedì","Tuesday"],["mercoledì","Wednesday"],["giovedì","Thursday"],["venerdì","Friday"],["sabato","Saturday"],["domenica","Sunday"],["gennaio","January"],["febbraio","February"],["marzo","March"],["aprile","April"],["maggio","May"],["giugno","June"],["luglio","July"],["agosto","August"],["settembre","September"],["ottobre","October"],["novembre","November"],["dicembre","December"],["la primavera","spring"],["l'estate","summer"],["l'autunno","autumn"],["l'inverno","winter"],["il fine settimana","the weekend"],["il compleanno","the birthday"],["la festa","the holiday / party"],["la data","the date"],["il calendario","the calendar"],["l'orologio","the clock / watch"],["il momento","the moment"]
]},
{cat:"Family & relationships", words:[
["la famiglia","the family"],["il padre","the father"],["la madre","the mother"],["i genitori","the parents"],["il figlio","the son"],["la figlia","the daughter"],["il fratello","the brother"],["la sorella","the sister"],["il nonno","the grandfather"],["la nonna","the grandmother"],["i nonni","the grandparents"],["il nipote","the grandson / nephew"],["la nipote","the granddaughter / niece"],["lo zio","the uncle"],["la zia","the aunt"],["il cugino","the cousin (m)"],["la cugina","the cousin (f)"],["il marito","the husband"],["la moglie","the wife"],["il fidanzato","the boyfriend / fiancé"],["la fidanzata","the girlfriend / fiancée"],["il bambino","the child (m)"],["la bambina","the child (f)"],["il ragazzo","the boy"],["la ragazza","the girl"],["l'uomo","the man"],["la donna","the woman"],["il signore","the gentleman / Mr"],["la signora","the lady / Mrs"],["l'amico","the friend (m)"],["l'amica","the friend (f)"],["il vicino","the neighbour"],["il collega","the colleague"],["il capo","the boss"],["l'ospite","the guest"],["lo sconosciuto","the stranger"],["il gemello","the twin"],["il suocero","the father-in-law"],["la suocera","the mother-in-law"],["il genero","the son-in-law"],["la nuora","the daughter-in-law"],["il cognato","the brother-in-law"],["il vedovo","the widower"],["la coppia","the couple"],["il matrimonio","the marriage / wedding"],["il divorzio","the divorce"],["l'amore","the love"],["il bacio","the kiss"],["l'abbraccio","the hug"],["l'amicizia","the friendship"]
]},
{cat:"The body", words:[
["il corpo","the body"],["la testa","the head"],["il capello","the hair (strand)"],["i capelli","the hair"],["il viso","the face"],["la faccia","the face"],["la fronte","the forehead"],["l'occhio","the eye"],["gli occhi","the eyes"],["il naso","the nose"],["la bocca","the mouth"],["il labbro","the lip"],["il dente","the tooth"],["la lingua","the tongue / language"],["l'orecchio","the ear"],["il collo","the neck"],["la gola","the throat"],["la spalla","the shoulder"],["il braccio","the arm"],["il gomito","the elbow"],["la mano","the hand"],["il dito","the finger"],["l'unghia","the nail"],["il petto","the chest"],["la schiena","the back"],["la pancia","the belly"],["lo stomaco","the stomach"],["la gamba","the leg"],["il ginocchio","the knee"],["il piede","the foot"],["la pelle","the skin"],["il cuore","the heart"],["il cervello","the brain"],["il polmone","the lung"],["il sangue","the blood"],["l'osso","the bone"],["il muscolo","the muscle"],["la voce","the voice"],["il respiro","the breath"],["la lacrima","the tear"],["il sorriso","the smile"],["la barba","the beard"],["il sopracciglio","the eyebrow"],["la guancia","the cheek"],["il mento","the chin"],["il polso","the wrist"],["la caviglia","the ankle"],["il fianco","the hip / side"],["il sederino","the bottom"],["la salute","the health"]
]},
{cat:"Food basics", words:[
["il cibo","the food"],["il pane","the bread"],["la pasta","the pasta"],["il riso","the rice"],["la pizza","the pizza"],["la carne","the meat"],["il pesce","the fish"],["il pollo","the chicken"],["il manzo","the beef"],["il maiale","the pork"],["il prosciutto","the ham"],["l'uovo","the egg"],["il formaggio","the cheese"],["il burro","the butter"],["l'olio","the oil"],["il sale","the salt"],["il pepe","the pepper"],["lo zucchero","the sugar"],["la farina","the flour"],["la zuppa","the soup"],["l'insalata","the salad"],["il panino","the sandwich"],["il dolce","the dessert / sweet"],["la torta","the cake"],["il biscotto","the cookie"],["il gelato","the ice cream"],["la cioccolata","the chocolate"],["la marmellata","the jam"],["il miele","the honey"],["lo yogurt","the yogurt"],["il latte","the milk"],["la panna","the cream"],["il sugo","the sauce"],["la salsa","the sauce"],["l'aceto","the vinegar"],["la spezia","the spice"],["la colazione","the breakfast"],["il pranzo","the lunch"],["la cena","the dinner"],["lo spuntino","the snack"],["la merenda","the afternoon snack"],["l'antipasto","the starter"],["il primo","the first course"],["il secondo","the main course"],["il contorno","the side dish"],["la ricetta","the recipe"],["la cucina","the kitchen / cuisine"],["il piatto","the plate / dish"],["la porzione","the portion"],["la fame","the hunger"]
]},
{cat:"Fruit & vegetables", words:[
["la frutta","the fruit"],["la mela","the apple"],["la pera","the pear"],["la banana","the banana"],["l'arancia","the orange"],["il limone","the lemon"],["l'uva","the grapes"],["la fragola","the strawberry"],["la ciliegia","the cherry"],["la pesca","the peach"],["l'albicocca","the apricot"],["la prugna","the plum"],["il melone","the melon"],["l'anguria","the watermelon"],["l'ananas","the pineapple"],["il kiwi","the kiwi"],["il fico","the fig"],["il mandarino","the tangerine"],["il pompelmo","the grapefruit"],["la verdura","the vegetable"],["il pomodoro","the tomato"],["la patata","the potato"],["la carota","the carrot"],["la cipolla","the onion"],["l'aglio","the garlic"],["il peperone","the bell pepper"],["la zucchina","the zucchini"],["la melanzana","the eggplant"],["il fagiolo","the bean"],["il pisello","the pea"],["il fungo","the mushroom"],["l'insalata","the lettuce"],["gli spinaci","the spinach"],["il broccolo","the broccoli"],["il cavolo","the cabbage"],["il sedano","the celery"],["il cetriolo","the cucumber"],["la zucca","the pumpkin"],["il mais","the corn"],["il prezzemolo","the parsley"],["il basilico","the basil"],["la lattuga","the lettuce"],["l'oliva","the olive"],["la noce","the walnut"],["la mandorla","the almond"],["la nocciola","the hazelnut"],["la castagna","the chestnut"],["il seme","the seed"],["la buccia","the peel"],["il nocciolo","the pit / stone"]
]},
{cat:"Drinks & dining", words:[
["la bevanda","the drink"],["l'acqua","the water"],["il caffè","the coffee"],["il tè","the tea"],["il latte","the milk"],["il succo","the juice"],["la spremuta","the fresh juice"],["il vino","the wine"],["la birra","the beer"],["lo spumante","the sparkling wine"],["il cocktail","the cocktail"],["la cioccolata calda","the hot chocolate"],["la limonata","the lemonade"],["l'aranciata","the orangeade"],["la bibita","the soft drink"],["il ghiaccio","the ice"],["il bicchiere","the glass"],["la tazza","the cup"],["la bottiglia","the bottle"],["la lattina","the can"],["la caraffa","the carafe"],["la cannuccia","the straw"],["il cameriere","the waiter"],["la cameriera","the waitress"],["il cuoco","the cook"],["il menù","the menu"],["il conto","the bill"],["la mancia","the tip"],["la prenotazione","the reservation"],["il tavolo","the table"],["la sedia","the chair"],["la tovaglia","the tablecloth"],["il tovagliolo","the napkin"],["la forchetta","the fork"],["il coltello","the knife"],["il cucchiaio","the spoon"],["il cucchiaino","the teaspoon"],["la posata","the cutlery"],["il vassoio","the tray"],["la sete","the thirst"],["il brindisi","the toast (cheers)"],["il bar","the café / bar"],["il ristorante","the restaurant"],["la trattoria","the trattoria"],["la pasticceria","the pastry shop"],["la gelateria","the ice-cream shop"],["la pizzeria","the pizzeria"],["il self-service","the self-service"],["la colazione","the breakfast"],["l'aperitivo","the aperitif"]
]},
{cat:"House & rooms", words:[
["la casa","the house"],["l'appartamento","the apartment"],["la stanza","the room"],["la camera","the bedroom"],["la cucina","the kitchen"],["il bagno","the bathroom"],["il salotto","the living room"],["la sala","the hall / room"],["lo studio","the study"],["la cantina","the cellar"],["la soffitta","the attic"],["il garage","the garage"],["il corridoio","the hallway"],["le scale","the stairs"],["il pavimento","the floor"],["il soffitto","the ceiling"],["il muro","the wall"],["la parete","the wall (interior)"],["la porta","the door"],["la finestra","the window"],["il balcone","the balcony"],["il terrazzo","the terrace"],["il giardino","the garden"],["il tetto","the roof"],["il camino","the fireplace"],["la chiave","the key"],["la serratura","the lock"],["il campanello","the doorbell"],["l'ascensore","the elevator"],["il riscaldamento","the heating"],["l'aria condizionata","the air conditioning"],["la luce","the light"],["la lampada","the lamp"],["la presa","the socket"],["l'interruttore","the switch"],["il mobile","the piece of furniture"],["il tavolo","the table"],["la sedia","the chair"],["il divano","the sofa"],["la poltrona","the armchair"],["il letto","the bed"],["l'armadio","the wardrobe"],["lo scaffale","the shelf"],["il cassetto","the drawer"],["lo specchio","the mirror"],["il tappeto","the carpet"],["la tenda","the curtain"],["il quadro","the painting"],["il vaso","the vase"],["l'affitto","the rent"]
]},
{cat:"Household objects", words:[
["il frigorifero","the fridge"],["il congelatore","the freezer"],["il forno","the oven"],["il fornello","the stove"],["il microonde","the microwave"],["la lavatrice","the washing machine"],["la lavastoviglie","the dishwasher"],["l'aspirapolvere","the vacuum cleaner"],["il ferro da stiro","the iron"],["la pentola","the pot"],["la padella","the pan"],["il coperchio","the lid"],["la teglia","the baking tray"],["il mestolo","the ladle"],["il tagliere","the cutting board"],["la grattugia","the grater"],["l'apriscatole","the can opener"],["il cavatappi","the corkscrew"],["la spugna","the sponge"],["il detersivo","the detergent"],["il sapone","the soap"],["lo shampoo","the shampoo"],["l'asciugamano","the towel"],["lo spazzolino","the toothbrush"],["il dentifricio","the toothpaste"],["il pettine","the comb"],["la spazzola","the brush"],["il rasoio","the razor"],["la carta igienica","the toilet paper"],["il secchio","the bucket"],["la scopa","the broom"],["lo straccio","the rag"],["il cestino","the bin"],["la spazzatura","the trash"],["la candela","the candle"],["i fiammiferi","the matches"],["l'accendino","the lighter"],["la pila","the battery"],["la torcia","the flashlight"],["il cuscino","the pillow"],["la coperta","the blanket"],["il lenzuolo","the sheet"],["il materasso","the mattress"],["la sveglia","the alarm clock"],["l'orologio","the clock"],["la cornice","the frame"],["l'attaccapanni","the coat rack"],["il portafoglio","the wallet"],["la borsa","the bag / handbag"],["la valigia","the suitcase"]
]},
{cat:"Clothing", words:[
["i vestiti","the clothes"],["l'abito","the dress / suit"],["la camicia","the shirt"],["la maglietta","the t-shirt"],["il maglione","the sweater"],["la felpa","the hoodie"],["i pantaloni","the trousers"],["i jeans","the jeans"],["i pantaloncini","the shorts"],["la gonna","the skirt"],["il vestito","the dress"],["la giacca","the jacket"],["il cappotto","the coat"],["il giubbotto","the jacket / coat"],["l'impermeabile","the raincoat"],["le scarpe","the shoes"],["gli stivali","the boots"],["i sandali","the sandals"],["le scarpe da ginnastica","the sneakers"],["le pantofole","the slippers"],["i calzini","the socks"],["le calze","the stockings"],["la biancheria","the underwear"],["le mutande","the underpants"],["il reggiseno","the bra"],["il pigiama","the pyjamas"],["il costume da bagno","the swimsuit"],["la cintura","the belt"],["la cravatta","the tie"],["la sciarpa","the scarf"],["i guanti","the gloves"],["il cappello","the hat"],["il berretto","the cap"],["gli occhiali","the glasses"],["gli occhiali da sole","the sunglasses"],["l'ombrello","the umbrella"],["la borsa","the bag"],["lo zaino","the backpack"],["il portafoglio","the wallet"],["l'orologio","the watch"],["l'anello","the ring"],["la collana","the necklace"],["gli orecchini","the earrings"],["il bracciale","the bracelet"],["la tasca","the pocket"],["il bottone","the button"],["la cerniera","the zipper"],["la taglia","the size"],["la moda","the fashion"],["il tessuto","the fabric"]
]},
{cat:"Colours & shapes", words:[
["il colore","the colour"],["rosso","red"],["arancione","orange"],["giallo","yellow"],["verde","green"],["blu","blue"],["azzurro","light blue"],["viola","purple"],["rosa","pink"],["marrone","brown"],["nero","black"],["bianco","white"],["grigio","grey"],["beige","beige"],["oro","gold"],["argento","silver"],["chiaro","light (colour)"],["scuro","dark"],["acceso","bright"],["spento","dull"],["la forma","the shape"],["il cerchio","the circle"],["il quadrato","the square"],["il triangolo","the triangle"],["il rettangolo","the rectangle"],["la linea","the line"],["il punto","the dot / point"],["la curva","the curve"],["la stella","the star"],["il cuore","the heart"],["tondo","round"],["dritto","straight"],["storto","crooked"],["piatto","flat"],["appuntito","pointy"],["la dimensione","the dimension"],["la misura","the measurement"],["l'altezza","the height"],["la larghezza","the width"],["la lunghezza","the length"],["la profondità","the depth"],["il peso","the weight"],["grande","big"],["piccolo","small"],["lungo","long"],["corto","short"],["largo","wide"],["stretto","narrow"],["alto","tall / high"],["basso","low / short"]
]},
{cat:"City & buildings", words:[
["la città","the city"],["il paese","the town / country"],["il villaggio","the village"],["il quartiere","the neighbourhood"],["il centro","the centre / downtown"],["la periferia","the suburbs"],["la strada","the street / road"],["la via","the street"],["il viale","the avenue"],["la piazza","the square"],["il marciapiede","the sidewalk"],["l'incrocio","the intersection"],["il semaforo","the traffic light"],["l'angolo","the corner"],["il ponte","the bridge"],["l'edificio","the building"],["il palazzo","the building / palace"],["il grattacielo","the skyscraper"],["la chiesa","the church"],["il duomo","the cathedral"],["il museo","the museum"],["il teatro","the theatre"],["il cinema","the cinema"],["la biblioteca","the library"],["la scuola","the school"],["l'università","the university"],["l'ospedale","the hospital"],["la farmacia","the pharmacy"],["la banca","the bank"],["l'ufficio postale","the post office"],["il negozio","the shop"],["il supermercato","the supermarket"],["il mercato","the market"],["il centro commerciale","the mall"],["il ristorante","the restaurant"],["l'albergo","the hotel"],["la stazione","the station"],["l'aeroporto","the airport"],["il parco","the park"],["il giardino pubblico","the public garden"],["lo stadio","the stadium"],["la palestra","the gym"],["la piscina","the swimming pool"],["il parcheggio","the parking lot"],["il distributore","the gas station"],["il municipio","the town hall"],["la stazione di polizia","the police station"],["la fontana","the fountain"],["il monumento","the monument"],["la torre","the tower"]
]},
{cat:"Travel & transport", words:[
["il viaggio","the trip"],["la vacanza","the holiday"],["il turista","the tourist"],["il passaporto","the passport"],["il biglietto","the ticket"],["il bagaglio","the luggage"],["la valigia","the suitcase"],["lo zaino","the backpack"],["la mappa","the map"],["la guida","the guide(book)"],["la macchina","the car"],["l'auto","the car"],["la moto","the motorcycle"],["la bicicletta","the bicycle"],["il treno","the train"],["l'autobus","the bus"],["il tram","the tram"],["la metropolitana","the subway"],["il taxi","the taxi"],["l'aereo","the plane"],["la nave","the ship"],["la barca","the boat"],["il traghetto","the ferry"],["il volo","the flight"],["il binario","the platform / track"],["la fermata","the stop"],["la coincidenza","the connection"],["il ritardo","the delay"],["l'arrivo","the arrival"],["la partenza","the departure"],["l'andata","the outward trip"],["il ritorno","the return"],["la dogana","the customs"],["la frontiera","the border"],["il confine","the border"],["il volante","the steering wheel"],["la ruota","the wheel"],["il motore","the engine"],["la benzina","the petrol"],["il gasolio","the diesel"],["la patente","the driving licence"],["la strada","the road"],["l'autostrada","the motorway"],["la curva","the bend"],["il pedaggio","the toll"],["il navigatore","the GPS"],["la cintura di sicurezza","the seatbelt"],["la velocità","the speed"],["la destinazione","the destination"],["il percorso","the route"]
]},
{cat:"Nature & geography", words:[
["la natura","nature"],["il mare","the sea"],["l'oceano","the ocean"],["il lago","the lake"],["il fiume","the river"],["il ruscello","the stream"],["la montagna","the mountain"],["la collina","the hill"],["la valle","the valley"],["la pianura","the plain"],["il bosco","the woods"],["la foresta","the forest"],["il deserto","the desert"],["l'isola","the island"],["la spiaggia","the beach"],["la sabbia","the sand"],["la roccia","the rock"],["la pietra","the stone"],["la terra","the earth / land"],["il cielo","the sky"],["il sole","the sun"],["la luna","the moon"],["la stella","the star"],["il pianeta","the planet"],["il mondo","the world"],["la campagna","the countryside"],["il prato","the meadow"],["il campo","the field"],["la grotta","the cave"],["la cascata","the waterfall"],["il vulcano","the volcano"],["il ghiacciaio","the glacier"],["la costa","the coast"],["la baia","the bay"],["il porto","the harbour"],["l'orizzonte","the horizon"],["il paesaggio","the landscape"],["l'ambiente","the environment"],["l'aria","the air"],["il fuoco","the fire"],["l'acqua","the water"],["il vento","the wind"],["l'onda","the wave"],["la marea","the tide"],["il fango","the mud"],["la polvere","the dust"],["il fumo","the smoke"],["la cenere","the ash"],["l'erba","the grass"],["la foglia","the leaf"]
]},
{cat:"Weather", words:[
["il tempo","the weather"],["il clima","the climate"],["il sole","the sun"],["la pioggia","the rain"],["la neve","the snow"],["il vento","the wind"],["la nuvola","the cloud"],["il temporale","the storm"],["il tuono","the thunder"],["il fulmine","the lightning"],["la nebbia","the fog"],["la grandine","the hail"],["il ghiaccio","the ice"],["la brina","the frost"],["l'arcobaleno","the rainbow"],["l'ombra","the shade / shadow"],["il caldo","the heat"],["il freddo","the cold"],["l'umidità","the humidity"],["la temperatura","the temperature"],["il grado","the degree"],["la previsione","the forecast"],["soleggiato","sunny"],["nuvoloso","cloudy"],["piovoso","rainy"],["ventoso","windy"],["nevoso","snowy"],["sereno","clear"],["coperto","overcast"],["afoso","muggy"],["mite","mild"],["gelido","freezing"],["bagnato","wet"],["asciutto","dry"],["la stagione","the season"],["il sudore","the sweat"],["l'acquazzone","the downpour"],["la pozzanghera","the puddle"],["il cielo","the sky"],["la goccia","the drop"],["il fiocco di neve","the snowflake"],["la raffica","the gust"],["la siccità","the drought"],["l'alluvione","the flood"],["il disgelo","the thaw"],["il sole splende","the sun shines"],["fa caldo","it's hot"],["fa freddo","it's cold"],["piove","it's raining"],["nevica","it's snowing"]
]},
{cat:"Animals", words:[
["l'animale","the animal"],["il cane","the dog"],["il gatto","the cat"],["il cavallo","the horse"],["la mucca","the cow"],["il toro","the bull"],["il maiale","the pig"],["la pecora","the sheep"],["la capra","the goat"],["il coniglio","the rabbit"],["la gallina","the hen"],["il gallo","the rooster"],["l'anatra","the duck"],["l'oca","the goose"],["il tacchino","the turkey"],["il topo","the mouse"],["il ratto","the rat"],["lo scoiattolo","the squirrel"],["il riccio","the hedgehog"],["la volpe","the fox"],["il lupo","the wolf"],["l'orso","the bear"],["il leone","the lion"],["la tigre","the tiger"],["l'elefante","the elephant"],["la giraffa","the giraffe"],["la scimmia","the monkey"],["il serpente","the snake"],["la lucertola","the lizard"],["la rana","the frog"],["la tartaruga","the turtle"],["il coccodrillo","the crocodile"],["il pesce","the fish"],["lo squalo","the shark"],["il delfino","the dolphin"],["la balena","the whale"],["il polpo","the octopus"],["il granchio","the crab"],["l'uccello","the bird"],["l'aquila","the eagle"],["il gufo","the owl"],["il piccione","the pigeon"],["il pappagallo","the parrot"],["l'ape","the bee"],["la farfalla","the butterfly"],["la mosca","the fly"],["la zanzara","the mosquito"],["il ragno","the spider"],["la formica","the ant"],["la coda","the tail"]
]},
{cat:"Plants & garden", words:[
["la pianta","the plant"],["l'albero","the tree"],["il fiore","the flower"],["l'erba","the grass"],["la foglia","the leaf"],["il ramo","the branch"],["il tronco","the trunk"],["la radice","the root"],["il seme","the seed"],["il frutto","the fruit"],["la rosa","the rose"],["il tulipano","the tulip"],["il girasole","the sunflower"],["la margherita","the daisy"],["il papavero","the poppy"],["la quercia","the oak"],["il pino","the pine"],["l'ulivo","the olive tree"],["la vite","the vine"],["il cespuglio","the bush"],["la siepe","the hedge"],["il giardino","the garden"],["l'orto","the vegetable garden"],["il vaso","the pot"],["la terra","the soil"],["il concime","the fertilizer"],["l'annaffiatoio","the watering can"],["la pala","the shovel"],["il rastrello","the rake"],["la zappa","the hoe"],["le forbici","the shears"],["il prato","the lawn"],["la spina","the thorn"],["il petalo","the petal"],["il polline","the pollen"],["il bocciolo","the bud"],["la corteccia","the bark"],["il muschio","the moss"],["il fungo","the mushroom"],["l'erbaccia","the weed"],["la serra","the greenhouse"],["il raccolto","the harvest"],["la fioritura","the bloom"],["la potatura","the pruning"],["coltivare","to grow / cultivate"],["piantare","to plant"],["annaffiare","to water"],["fiorire","to bloom"],["crescere","to grow"],["appassire","to wither"]
]},
{cat:"Work & professions", words:[
["il lavoro","the work / job"],["il mestiere","the trade"],["la professione","the profession"],["la carriera","the career"],["l'azienda","the company"],["la ditta","the firm"],["l'ufficio","the office"],["il capo","the boss"],["il dipendente","the employee"],["il collega","the colleague"],["il cliente","the client"],["lo stipendio","the salary"],["il contratto","the contract"],["la riunione","the meeting"],["l'appuntamento","the appointment"],["la scadenza","the deadline"],["il progetto","the project"],["il compito","the task"],["la pausa","the break"],["le ferie","the holidays (work)"],["il medico","the doctor"],["l'infermiere","the nurse"],["l'insegnante","the teacher"],["il professore","the professor"],["l'avvocato","the lawyer"],["l'ingegnere","the engineer"],["l'architetto","the architect"],["il commercialista","the accountant"],["il dentista","the dentist"],["il veterinario","the vet"],["il poliziotto","the police officer"],["il pompiere","the firefighter"],["il cuoco","the cook / chef"],["il cameriere","the waiter"],["il commesso","the shop assistant"],["il meccanico","the mechanic"],["l'elettricista","the electrician"],["l'idraulico","the plumber"],["il muratore","the builder"],["il contadino","the farmer"],["il giardiniere","the gardener"],["il pittore","the painter"],["il musicista","the musician"],["lo scrittore","the writer"],["il giornalista","the journalist"],["l'attore","the actor"],["il pilota","the pilot"],["il marinaio","the sailor"],["il soldato","the soldier"],["il direttore","the director / manager"]
]},
{cat:"Money & shopping", words:[
["i soldi","the money"],["il denaro","the money"],["l'euro","the euro"],["il centesimo","the cent"],["la moneta","the coin"],["la banconota","the banknote"],["il prezzo","the price"],["il costo","the cost"],["lo sconto","the discount"],["i saldi","the sales"],["l'offerta","the offer"],["il conto","the bill / account"],["la ricevuta","the receipt"],["lo scontrino","the receipt"],["la fattura","the invoice"],["la carta di credito","the credit card"],["il bancomat","the ATM / debit card"],["il contante","the cash"],["il resto","the change"],["il portafoglio","the wallet"],["la cassa","the checkout"],["il carrello","the cart"],["il cestino","the basket"],["la borsa","the bag"],["il negozio","the shop"],["la vetrina","the shop window"],["il prodotto","the product"],["la marca","the brand"],["la qualità","the quality"],["la quantità","the quantity"],["il cliente","the customer"],["il commesso","the salesperson"],["la spesa","the shopping / expense"],["l'acquisto","the purchase"],["la vendita","the sale"],["il magazzino","the warehouse"],["la consegna","the delivery"],["la garanzia","the warranty"],["il rimborso","the refund"],["la tassa","the tax"],["l'IVA","the VAT"],["il risparmio","the savings"],["il prestito","the loan"],["il debito","the debt"],["il guadagno","the earnings"],["la spesa","the expense"],["il bilancio","the budget"],["ricco","rich"],["povero","poor"],["gratis","free (no cost)"]
]},
{cat:"School & education", words:[
["la scuola","the school"],["l'asilo","the kindergarten"],["le elementari","the primary school"],["le medie","the middle school"],["il liceo","the high school"],["l'università","the university"],["lo studente","the student"],["l'alunno","the pupil"],["il maestro","the teacher (primary)"],["il professore","the teacher / professor"],["il preside","the principal"],["la classe","the class"],["l'aula","the classroom"],["la lezione","the lesson"],["la materia","the subject"],["la matematica","mathematics"],["la storia","history"],["la geografia","geography"],["la scienza","science"],["la chimica","chemistry"],["la fisica","physics"],["la biologia","biology"],["la letteratura","literature"],["la lingua","the language"],["l'arte","art"],["la musica","music"],["la ginnastica","P.E."],["il compito","the homework"],["l'esame","the exam"],["il voto","the grade"],["la pagella","the report card"],["il diploma","the diploma"],["la laurea","the degree"],["la borsa di studio","the scholarship"],["il libro","the book"],["il quaderno","the notebook"],["la penna","the pen"],["la matita","the pencil"],["la gomma","the eraser"],["il righello","the ruler"],["la lavagna","the blackboard"],["lo zaino","the backpack"],["l'astuccio","the pencil case"],["il banco","the desk"],["la biblioteca","the library"],["lo studio","the study"],["la ricerca","the research"],["la domanda","the question"],["la risposta","the answer"],["l'errore","the mistake"]
]},
{cat:"Technology", words:[
["la tecnologia","the technology"],["il computer","the computer"],["il portatile","the laptop"],["il telefono","the phone"],["il cellulare","the mobile phone"],["lo smartphone","the smartphone"],["il tablet","the tablet"],["lo schermo","the screen"],["la tastiera","the keyboard"],["il mouse","the mouse"],["la stampante","the printer"],["la fotocamera","the camera"],["la cuffia","the headphones"],["l'altoparlante","the speaker"],["il caricabatterie","the charger"],["la batteria","the battery"],["il cavo","the cable"],["internet","the internet"],["il wifi","the wifi"],["la rete","the network"],["il sito","the website"],["la pagina","the page"],["l'applicazione","the application"],["l'app","the app"],["il programma","the program"],["il software","the software"],["il file","the file"],["la cartella","the folder"],["il documento","the document"],["la password","the password"],["l'account","the account"],["l'utente","the user"],["la mail","the email"],["il messaggio","the message"],["la chiamata","the call"],["la videochiamata","the video call"],["la foto","the photo"],["il video","the video"],["il social","the social media"],["il gioco","the game"],["il dato","the data"],["la memoria","the memory"],["lo spazio","the storage"],["l'aggiornamento","the update"],["il virus","the virus"],["il motore di ricerca","the search engine"],["il collegamento","the link"],["scaricare","to download"],["caricare","to upload"],["cliccare","to click"]
]},
{cat:"Emotions & feelings", words:[
["il sentimento","the feeling"],["l'emozione","the emotion"],["la felicità","the happiness"],["la gioia","the joy"],["la tristezza","the sadness"],["la rabbia","the anger"],["la paura","the fear"],["la sorpresa","the surprise"],["l'amore","the love"],["l'odio","the hatred"],["la speranza","the hope"],["la gelosia","the jealousy"],["l'invidia","the envy"],["la vergogna","the shame"],["la noia","the boredom"],["lo stress","the stress"],["l'ansia","the anxiety"],["la calma","the calm"],["la pace","the peace"],["il coraggio","the courage"],["la fiducia","the trust"],["il dubbio","the doubt"],["la curiosità","the curiosity"],["la delusione","the disappointment"],["il piacere","the pleasure"],["il dolore","the pain / grief"],["felice","happy"],["contento","glad"],["triste","sad"],["arrabbiato","angry"],["spaventato","scared"],["stanco","tired"],["annoiato","bored"],["nervoso","nervous"],["preoccupato","worried"],["sorpreso","surprised"],["emozionato","excited"],["deluso","disappointed"],["geloso","jealous"],["orgoglioso","proud"],["soddisfatto","satisfied"],["confuso","confused"],["sollevato","relieved"],["commosso","moved (emotionally)"],["entusiasta","enthusiastic"],["tranquillo","calm"],["sereno","serene"],["allegro","cheerful"],["depresso","depressed"],["solo","lonely / alone"]
]},
{cat:"Character & personality", words:[
["il carattere","the character"],["la personalità","the personality"],["gentile","kind"],["simpatico","likeable"],["antipatico","unpleasant"],["bravo","good / skilled"],["cattivo","bad / mean"],["buono","good"],["generoso","generous"],["egoista","selfish"],["onesto","honest"],["bugiardo","liar / lying"],["sincero","sincere"],["timido","shy"],["socievole","sociable"],["allegro","cheerful"],["serio","serious"],["divertente","funny"],["noioso","boring"],["intelligente","intelligent"],["furbo","clever / cunning"],["stupido","stupid"],["saggio","wise"],["pigro","lazy"],["lavoratore","hard-working"],["coraggioso","brave"],["pauroso","fearful"],["paziente","patient"],["impaziente","impatient"],["calmo","calm"],["nervoso","nervous"],["educato","polite"],["maleducato","rude"],["orgoglioso","proud"],["umile","humble"],["testardo","stubborn"],["curioso","curious"],["creativo","creative"],["affidabile","reliable"],["responsabile","responsible"],["ambizioso","ambitious"],["modesto","modest"],["sensibile","sensitive"],["forte","strong"],["debole","weak"],["dolce","sweet / gentle"],["severo","strict"],["aperto","open"],["chiuso","reserved"],["affettuoso","affectionate"]
]},
{cat:"Common adjectives I", words:[
["grande","big"],["piccolo","small"],["lungo","long"],["corto","short"],["alto","tall / high"],["basso","low / short"],["largo","wide"],["stretto","narrow"],["grosso","thick / big"],["sottile","thin"],["pesante","heavy"],["leggero","light"],["nuovo","new"],["vecchio","old"],["giovane","young"],["antico","ancient"],["moderno","modern"],["bello","beautiful"],["brutto","ugly"],["buono","good"],["cattivo","bad"],["facile","easy"],["difficile","difficult"],["semplice","simple"],["complicato","complicated"],["importante","important"],["utile","useful"],["inutile","useless"],["necessario","necessary"],["possibile","possible"],["impossibile","impossible"],["vero","true"],["falso","false"],["giusto","right / fair"],["sbagliato","wrong"],["sicuro","safe / sure"],["pericoloso","dangerous"],["pulito","clean"],["sporco","dirty"],["pieno","full"],["vuoto","empty"],["aperto","open"],["chiuso","closed"],["caldo","hot"],["freddo","cold"],["bagnato","wet"],["asciutto","dry"],["duro","hard"],["morbido","soft"],["liscio","smooth"]
]},
{cat:"Common adjectives II", words:[
["veloce","fast"],["lento","slow"],["forte","strong / loud"],["piano","soft / slow"],["ricco","rich"],["povero","poor"],["caro","expensive / dear"],["economico","cheap"],["gratis","free"],["raro","rare"],["comune","common"],["strano","strange"],["normale","normal"],["speciale","special"],["famoso","famous"],["sconosciuto","unknown"],["felice","happy"],["fortunato","lucky"],["sfortunato","unlucky"],["libero","free / available"],["occupato","busy / taken"],["stanco","tired"],["sveglio","awake / sharp"],["malato","sick"],["sano","healthy"],["fresco","fresh / cool"],["maturo","ripe / mature"],["dolce","sweet"],["amaro","bitter"],["salato","salty"],["piccante","spicy"],["acido","sour"],["delizioso","delicious"],["disgustoso","disgusting"],["luminoso","bright"],["buio","dark"],["rumoroso","noisy"],["silenzioso","quiet"],["profondo","deep"],["superficiale","shallow"],["spesso","thick / often"],["fine","fine / thin"],["intero","whole"],["mezzo","half"],["doppio","double"],["singolo","single"],["pronto","ready"],["finito","finished"],["rotto","broken"],["perfetto","perfect"]
]},
{cat:"Sports & hobbies", words:[
["lo sport","the sport"],["il gioco","the game"],["il calcio","football"],["il basket","basketball"],["il tennis","tennis"],["la pallavolo","volleyball"],["il nuoto","swimming"],["la corsa","running"],["il ciclismo","cycling"],["lo sci","skiing"],["il golf","golf"],["la boxe","boxing"],["la palestra","the gym"],["l'allenamento","the training"],["la partita","the match"],["la squadra","the team"],["il giocatore","the player"],["l'arbitro","the referee"],["l'allenatore","the coach"],["il tifoso","the fan"],["la vittoria","the victory"],["la sconfitta","the defeat"],["il pareggio","the draw"],["il punteggio","the score"],["il campionato","the championship"],["la coppa","the cup"],["la medaglia","the medal"],["il premio","the prize"],["il record","the record"],["il pallone","the ball"],["la racchetta","the racket"],["la rete","the net / goal"],["il campo","the field / court"],["il passatempo","the hobby"],["la lettura","reading"],["la fotografia","photography"],["il disegno","drawing"],["la pittura","painting"],["il giardinaggio","gardening"],["la pesca","fishing"],["la caccia","hunting"],["il campeggio","camping"],["l'escursione","the hike"],["il viaggio","travelling"],["la danza","dance"],["il canto","singing"],["la cucina","cooking"],["il collezionismo","collecting"],["il puzzle","the puzzle"],["la scacchiera","the chessboard"]
]},
{cat:"Arts, media & culture", words:[
["l'arte","the art"],["la musica","the music"],["la canzone","the song"],["il cantante","the singer"],["la band","the band"],["lo strumento","the instrument"],["il pianoforte","the piano"],["la chitarra","the guitar"],["il violino","the violin"],["la batteria","the drums"],["il concerto","the concert"],["il film","the film"],["il cinema","the cinema"],["l'attore","the actor"],["l'attrice","the actress"],["il regista","the director"],["la scena","the scene"],["il teatro","the theatre"],["lo spettacolo","the show"],["il biglietto","the ticket"],["il pubblico","the audience"],["il libro","the book"],["il romanzo","the novel"],["la poesia","the poem / poetry"],["la storia","the story"],["l'autore","the author"],["lo scrittore","the writer"],["il giornale","the newspaper"],["la rivista","the magazine"],["la notizia","the news"],["la televisione","the television"],["il programma","the programme"],["il canale","the channel"],["la pubblicità","the advertising"],["la radio","the radio"],["il quadro","the painting"],["la pittura","the painting (art)"],["la scultura","the sculpture"],["la mostra","the exhibition"],["la galleria","the gallery"],["il museo","the museum"],["la fotografia","the photograph"],["la cultura","the culture"],["la tradizione","the tradition"],["la festa","the festival / party"],["il festival","the festival"],["il colore","the colour"],["il disegno","the drawing"],["la danza","the dance"],["il capolavoro","the masterpiece"]
]},
{cat:"Communication & language", words:[
["la lingua","the language"],["la parola","the word"],["la frase","the sentence"],["il significato","the meaning"],["la voce","the voice"],["il suono","the sound"],["l'accento","the accent"],["la pronuncia","the pronunciation"],["la grammatica","the grammar"],["il verbo","the verb"],["il nome","the noun / name"],["l'aggettivo","the adjective"],["la traduzione","the translation"],["il dizionario","the dictionary"],["il discorso","the speech"],["la conversazione","the conversation"],["la domanda","the question"],["la risposta","the answer"],["l'opinione","the opinion"],["l'idea","the idea"],["il consiglio","the advice"],["la spiegazione","the explanation"],["l'esempio","the example"],["la storia","the story"],["la bugia","the lie"],["la verità","the truth"],["il segreto","the secret"],["la promessa","the promise"],["la scusa","the excuse / apology"],["il saluto","the greeting"],["il messaggio","the message"],["la lettera","the letter"],["la firma","the signature"],["il silenzio","the silence"],["il rumore","the noise"],["dire","to say"],["parlare","to speak"],["chiedere","to ask"],["rispondere","to answer"],["raccontare","to tell"],["spiegare","to explain"],["tradurre","to translate"],["leggere","to read"],["scrivere","to write"],["ascoltare","to listen"],["capire","to understand"],["ripetere","to repeat"],["pronunciare","to pronounce"],["discutere","to discuss"],["sussurrare","to whisper"]
]},
{cat:"Abstract & ideas", words:[
["l'idea","the idea"],["il pensiero","the thought"],["la mente","the mind"],["la memoria","the memory"],["il sogno","the dream"],["la verità","the truth"],["la realtà","the reality"],["il fatto","the fact"],["la ragione","the reason"],["la causa","the cause"],["l'effetto","the effect"],["il risultato","the result"],["lo scopo","the purpose"],["il motivo","the motive"],["il problema","the problem"],["la soluzione","the solution"],["la scelta","the choice"],["la decisione","the decision"],["il rischio","the risk"],["la possibilità","the possibility"],["l'occasione","the opportunity"],["la fortuna","the luck / fortune"],["il destino","the destiny"],["il caso","the case / chance"],["il modo","the way"],["il metodo","the method"],["il sistema","the system"],["la regola","the rule"],["la legge","the law"],["il diritto","the right"],["il dovere","the duty"],["la libertà","the freedom"],["la giustizia","the justice"],["la pace","the peace"],["la guerra","the war"],["il potere","the power"],["la forza","the strength / force"],["l'energia","the energy"],["la vita","the life"],["la morte","the death"],["il futuro","the future"],["il passato","the past"],["il presente","the present"],["il cambiamento","the change"],["il progresso","the progress"],["l'esperienza","the experience"],["la conoscenza","the knowledge"],["l'abitudine","the habit"],["il valore","the value"],["l'importanza","the importance"]
]},
{cat:"Materials, tools & misc", words:[
["il materiale","the material"],["il legno","the wood"],["il metallo","the metal"],["il ferro","the iron"],["l'acciaio","the steel"],["l'oro","the gold"],["l'argento","the silver"],["il rame","the copper"],["la plastica","the plastic"],["il vetro","the glass"],["la carta","the paper"],["il cartone","the cardboard"],["la stoffa","the cloth"],["il cotone","the cotton"],["la lana","the wool"],["la seta","the silk"],["la pelle","the leather / skin"],["la gomma","the rubber"],["il cemento","the cement"],["il mattone","the brick"],["lo strumento","the tool"],["il martello","the hammer"],["il chiodo","the nail"],["la vite","the screw"],["il cacciavite","the screwdriver"],["la chiave inglese","the wrench"],["la sega","the saw"],["il trapano","the drill"],["le forbici","the scissors"],["il nastro","the tape"],["la colla","the glue"],["la corda","the rope"],["il filo","the thread / wire"],["la catena","the chain"],["il tubo","the pipe"],["la scatola","the box"],["il sacchetto","the bag"],["la borsa","the bag"],["il contenitore","the container"],["il barattolo","the jar"],["la bottiglia","the bottle"],["il coperchio","the lid"],["l'etichetta","the label"],["il cartello","the sign"],["la maniglia","the handle"],["la rotella","the wheel (small)"],["la molla","the spring"],["l'ingranaggio","the gear"],["la macchina","the machine"],["il pezzo","the part / piece"]
]},
{cat:"Everyday actions IV", words:[
["aggiungere","to add"],["togliere","to remove"],["girare","to turn"],["tagliare","to cut"],["piegare","to fold"],["legare","to tie"],["sciogliere","to untie / melt"],["versare","to pour"],["mescolare","to mix"],["scuotere","to shake"],["premere","to press"],["toccare","to touch"],["afferrare","to grab"],["lanciare","to throw"],["raccogliere","to pick up"],["nascondere","to hide"],["mostrare","to show"],["coprire","to cover"],["scoprire","to uncover / discover"],["appendere","to hang"],["accendere","to turn on"],["spegnere","to turn off"],["collegare","to connect"],["staccare","to unplug"],["spostare","to move (something)"],["sollevare","to lift"],["abbassare","to lower"],["alzare","to raise"],["riempire","to fill"],["svuotare","to empty"],["pesare","to weigh"],["misurare","to measure"],["contare","to count"],["calcolare","to calculate"],["disegnare","to draw"],["dipingere","to paint"],["fotografare","to photograph"],["registrare","to record"],["filmare","to film"],["stampare","to print"],["copiare","to copy"],["incollare","to paste"],["cancellare","to delete / erase"],["salvare","to save"],["condividere","to share"],["scambiare","to exchange"],["prestare","to lend"],["restituire","to give back"],["rubare","to steal"],["proteggere","to protect"]
]},
{cat:"More useful nouns", words:[
["la cosa","the thing"],["il posto","the place"],["il luogo","the place"],["la persona","the person"],["la gente","the people"],["il gruppo","the group"],["la parte","the part"],["il lato","the side"],["il centro","the centre"],["il bordo","the edge"],["il fondo","the bottom"],["la cima","the top"],["la fine","the end"],["l'inizio","the beginning"],["il mezzo","the middle / means"],["la fila","the line / row"],["l'ordine","the order"],["il modo","the way"],["la maniera","the manner"],["la situazione","the situation"],["il problema","the problem"],["la difficoltà","the difficulty"],["il vantaggio","the advantage"],["lo svantaggio","the disadvantage"],["la differenza","the difference"],["la somiglianza","the similarity"],["il confronto","the comparison"],["l'esempio","the example"],["il dettaglio","the detail"],["il resto","the rest"],["l'insieme","the whole / set"],["la coppia","the pair"],["la serie","the series"],["il tipo","the type"],["la specie","the kind / species"],["la categoria","the category"],["il livello","the level"],["il grado","the degree"],["la misura","the measure"],["la quantità","the quantity"],["la qualità","the quality"],["il valore","the value"],["il prezzo","the price"],["il costo","the cost"],["la spesa","the expense"],["il bisogno","the need"],["la voglia","the desire"],["la fretta","the rush"],["la pausa","the break"],["il turno","the turn / shift"]
]},
{cat:"Adjectives III & opposites", words:[
["primo","first"],["ultimo","last"],["prossimo","next"],["scorso","last (past)"],["intero","whole"],["parziale","partial"],["completo","complete"],["vuoto","empty"],["pieno","full"],["aperto","open"],["chiuso","closed"],["acceso","on / lit"],["spento","off"],["presente","present"],["assente","absent"],["uguale","equal / same"],["diverso","different"],["simile","similar"],["opposto","opposite"],["medio","average / medium"],["massimo","maximum"],["minimo","minimum"],["principale","main"],["secondario","secondary"],["generale","general"],["particolare","particular"],["pubblico","public"],["privato","private"],["personale","personal"],["comune","common"],["nazionale","national"],["internazionale","international"],["locale","local"],["centrale","central"],["finale","final"],["iniziale","initial"],["vero","real / true"],["finto","fake"],["naturale","natural"],["artificiale","artificial"],["legale","legal"],["illegale","illegal"],["giusto","fair / correct"],["ingiusto","unfair"],["positivo","positive"],["negativo","negative"],["attivo","active"],["passivo","passive"],["disponibile","available"],["impegnato","busy"]
]},
{cat:"World & society", words:[
["il paese","the country"],["la nazione","the nation"],["lo stato","the state"],["il governo","the government"],["il popolo","the people / nation"],["il cittadino","the citizen"],["la legge","the law"],["la politica","the politics"],["il presidente","the president"],["il sindaco","the mayor"],["il re","the king"],["la regina","the queen"],["la guerra","the war"],["la pace","the peace"],["la storia","the history"],["la società","the society"],["la cultura","the culture"],["la religione","the religion"],["la chiesa","the church"],["Dio","God"],["il mondo","the world"],["l'Europa","Europe"],["l'Italia","Italy"],["la Francia","France"],["la Germania","Germany"],["la Spagna","Spain"],["l'Inghilterra","England"],["gli Stati Uniti","the United States"],["italiano","Italian"],["francese","French"],["tedesco","German"],["spagnolo","Spanish"],["inglese","English"],["americano","American"],["europeo","European"],["straniero","foreign / foreigner"],["la lingua","the language"],["la bandiera","the flag"],["il confine","the border"],["la capitale","the capital"],["il continente","the continent"],["il mare","the sea"],["l'economia","the economy"],["il lavoro","the labour"],["la libertà","the freedom"],["il diritto","the right"],["la pace","the peace"],["l'ambiente","the environment"],["la natura","nature"],["il futuro","the future"]
]}
];

const PHRASE_GROUPS = [
{cat:"Greetings & politeness", phrases:[
["Ciao!","Hi! / Bye!"],["Buongiorno","Good morning"],["Buon pomeriggio","Good afternoon"],["Buonasera","Good evening"],["Buonanotte","Good night"],["Arrivederci","Goodbye"],["A presto","See you soon"],["A dopo","See you later"],["A domani","See you tomorrow"],["Ci vediamo","See you"],["Grazie","Thank you"],["Grazie mille","Thank you very much"],["Prego","You're welcome"],["Per favore","Please"],["Per piacere","Please"],["Scusa","Excuse me / sorry (informal)"],["Mi scusi","Excuse me (formal)"],["Permesso","May I pass?"],["Di niente","Don't mention it"],["Salve","Hello (neutral)"]
]},
{cat:"Introductions & small talk", phrases:[
["Come ti chiami?","What's your name?"],["Mi chiamo Marco","My name is Marco"],["Piacere di conoscerti","Nice to meet you"],["Piacere mio","My pleasure"],["Come stai?","How are you? (informal)"],["Come sta?","How are you? (formal)"],["Come va?","How's it going?"],["Sto bene, grazie","I'm well, thanks"],["Non c'è male","Not bad"],["E tu?","And you?"],["Di dove sei?","Where are you from?"],["Sono americano","I'm American"],["Vengo dagli Stati Uniti","I'm from the United States"],["Dove abiti?","Where do you live?"],["Abito a Roma","I live in Rome"],["Quanti anni hai?","How old are you?"],["Ho venticinque anni","I'm twenty-five"],["Che lavoro fai?","What do you do for work?"],["Sono uno studente","I'm a student"],["Benvenuto!","Welcome!"]
]},
{cat:"Basic questions", phrases:[
["Cosa?","What?"],["Chi?","Who?"],["Dove?","Where?"],["Quando?","When?"],["Perché?","Why?"],["Come?","How?"],["Quanto costa?","How much does it cost?"],["Quanti sono?","How many are there?"],["Che cos'è questo?","What is this?"],["Che ora è?","What time is it?"],["Dov'è il bagno?","Where is the bathroom?"],["Cosa significa?","What does it mean?"],["Come si dice in italiano?","How do you say it in Italian?"],["Come si scrive?","How do you spell it?"],["Posso?","May I?"],["È possibile?","Is it possible?"],["C'è un problema?","Is there a problem?"],["Va bene?","Is that okay?"],["Sei sicuro?","Are you sure?"],["Davvero?","Really?"]
]},
{cat:"Help & understanding", phrases:[
["Mi può aiutare?","Can you help me?"],["Ho bisogno di aiuto","I need help"],["Non capisco","I don't understand"],["Non lo so","I don't know"],["Può ripetere, per favore?","Can you repeat, please?"],["Può parlare più lentamente?","Can you speak more slowly?"],["Parla inglese?","Do you speak English?"],["Parlo poco italiano","I speak a little Italian"],["Non parlo bene l'italiano","I don't speak Italian well"],["Come, scusa?","Sorry, what?"],["Cosa hai detto?","What did you say?"],["Può scriverlo?","Can you write it down?"],["Un momento, per favore","One moment, please"],["Aspetta!","Wait!"],["Non sono sicuro","I'm not sure"],["Capisco","I understand"],["Ho capito","I got it"],["Adesso è chiaro","Now it's clear"],["Mi dispiace, non lo sapevo","Sorry, I didn't know"],["Può aiutarmi con questo?","Can you help me with this?"]
]},
{cat:"Directions & getting around", phrases:[
["Dov'è la stazione?","Where is the station?"],["Come arrivo al centro?","How do I get downtown?"],["È lontano?","Is it far?"],["È vicino?","Is it near?"],["A sinistra","To the left"],["A destra","To the right"],["Sempre dritto","Straight ahead"],["Gira a destra","Turn right"],["Giri a sinistra","Turn left (formal)"],["Al semaforo","At the traffic light"],["Al prossimo incrocio","At the next intersection"],["Mi sono perso","I'm lost"],["Sto cercando questo indirizzo","I'm looking for this address"],["Può mostrarmelo sulla mappa?","Can you show me on the map?"],["Quanto ci vuole?","How long does it take?"],["Ci vogliono dieci minuti","It takes ten minutes"],["È qui vicino","It's nearby"],["Dietro l'angolo","Around the corner"],["Di fronte alla banca","Across from the bank"],["Accanto al supermercato","Next to the supermarket"]
]},
{cat:"At the restaurant", phrases:[
["Un tavolo per due, per favore","A table for two, please"],["Avete un tavolo libero?","Do you have a free table?"],["Il menù, per favore","The menu, please"],["Cosa mi consiglia?","What do you recommend?"],["Vorrei ordinare","I'd like to order"],["Per me la pasta","Pasta for me"],["Da bere, prendo acqua","To drink, I'll have water"],["Acqua naturale o frizzante?","Still or sparkling water?"],["È piccante?","Is it spicy?"],["Sono vegetariano","I'm vegetarian"],["Sono allergico alle noci","I'm allergic to nuts"],["È tutto buonissimo","It's all delicious"],["Ancora un po' di pane, per favore","A bit more bread, please"],["Il conto, per favore","The bill, please"],["Possiamo pagare separatamente?","Can we pay separately?"],["Accettate carte?","Do you take cards?"],["Tenga il resto","Keep the change"],["Un caffè, per favore","A coffee, please"],["Buon appetito!","Enjoy your meal!"],["Era squisito, grazie","It was exquisite, thank you"]
]},
{cat:"Shopping & money", phrases:[
["Quanto costa questo?","How much is this?"],["È troppo caro","It's too expensive"],["Avete qualcosa di più economico?","Do you have anything cheaper?"],["Posso provarlo?","Can I try it on?"],["Che taglia è?","What size is it?"],["Avete una taglia più grande?","Do you have a bigger size?"],["Lo prendo","I'll take it"],["Sto solo guardando","I'm just looking"],["C'è uno sconto?","Is there a discount?"],["È in saldo?","Is it on sale?"],["Posso pagare con carta?","Can I pay by card?"],["Pago in contanti","I'll pay cash"],["Mi può fare lo scontrino?","Can I have the receipt?"],["Vorrei un rimborso","I'd like a refund"],["Dov'è la cassa?","Where is the checkout?"],["Avete questo in un altro colore?","Do you have this in another colour?"],["A che ora chiudete?","What time do you close?"],["È aperto la domenica?","Is it open on Sunday?"],["Mi serve una borsa","I need a bag"],["Va bene così, grazie","That's all, thanks"]
]},
{cat:"At the hotel", phrases:[
["Ho una prenotazione","I have a reservation"],["Vorrei prenotare una camera","I'd like to book a room"],["Avete camere libere?","Do you have rooms available?"],["Una camera singola","A single room"],["Una camera doppia","A double room"],["Per quante notti?","For how many nights?"],["Per tre notti","For three nights"],["Quanto costa a notte?","How much per night?"],["È inclusa la colazione?","Is breakfast included?"],["A che ora è la colazione?","What time is breakfast?"],["Ecco la chiave","Here is the key"],["Qual è il wifi?","What's the wifi?"],["Il riscaldamento non funziona","The heating isn't working"],["L'aria condizionata non va","The A/C doesn't work"],["Posso avere asciugamani puliti?","Can I have clean towels?"],["A che ora è il check-out?","What time is check-out?"],["Posso lasciare i bagagli?","Can I leave my luggage?"],["La camera è molto bella","The room is very nice"],["C'è troppo rumore","There's too much noise"],["Vorrei fare il check-out","I'd like to check out"]
]},
{cat:"Travel & transport", phrases:[
["Un biglietto, per favore","One ticket, please"],["Due biglietti per Firenze","Two tickets to Florence"],["Solo andata o andata e ritorno?","One way or round trip?"],["A che ora parte il treno?","What time does the train leave?"],["Da quale binario?","From which platform?"],["Il treno è in ritardo","The train is late"],["Ho perso il treno","I missed the train"],["È questo il treno per Milano?","Is this the train to Milan?"],["Quanto dura il viaggio?","How long is the journey?"],["Dove devo cambiare?","Where do I change?"],["Questo posto è libero?","Is this seat free?"],["Dov'è la fermata dell'autobus?","Where is the bus stop?"],["Quale autobus va in centro?","Which bus goes downtown?"],["Mi può chiamare un taxi?","Can you call me a taxi?"],["Mi porti a questo indirizzo","Take me to this address"],["Quanto le devo?","How much do I owe you?"],["Vorrei noleggiare un'auto","I'd like to rent a car"],["Dov'è il distributore?","Where is the gas station?"],["Il volo è in orario?","Is the flight on time?"],["Dov'è il gate?","Where is the gate?"]
]},
{cat:"Time & dates", phrases:[
["Che ora è?","What time is it?"],["Sono le tre","It's three o'clock"],["È l'una","It's one o'clock"],["Sono le sette e mezza","It's seven thirty"],["È mezzogiorno","It's noon"],["A che ora?","At what time?"],["Alle otto di mattina","At eight in the morning"],["Nel pomeriggio","In the afternoon"],["Di sera","In the evening"],["Che giorno è oggi?","What day is it today?"],["Oggi è lunedì","Today is Monday"],["Qual è la data?","What's the date?"],["È il primo maggio","It's the first of May"],["Tra un'ora","In an hour"],["Tra due giorni","In two days"],["La settimana prossima","Next week"],["Il mese scorso","Last month"],["In orario","On time"],["In anticipo","Early"],["Sono in ritardo","I'm late"]
]},
{cat:"Emergencies & health", phrases:[
["Aiuto!","Help!"],["Chiama un'ambulanza!","Call an ambulance!"],["Chiama la polizia!","Call the police!"],["È un'emergenza","It's an emergency"],["Ho bisogno di un medico","I need a doctor"],["Non mi sento bene","I don't feel well"],["Mi fa male qui","It hurts here"],["Ho mal di testa","I have a headache"],["Ho mal di stomaco","I have a stomachache"],["Ho la febbre","I have a fever"],["Sono allergico","I'm allergic"],["Dov'è la farmacia?","Where is the pharmacy?"],["Dov'è l'ospedale?","Where is the hospital?"],["Mi serve una medicina","I need a medicine"],["Ho perso il passaporto","I've lost my passport"],["Mi hanno rubato la borsa","My bag was stolen"],["Attenzione!","Watch out!"],["Al fuoco!","Fire!"],["Sto male","I feel sick"],["Può chiamare aiuto?","Can you call for help?"]
]},
{cat:"Weather & opinions", phrases:[
["Che tempo fa?","What's the weather like?"],["Fa caldo","It's hot"],["Fa freddo","It's cold"],["Fa bel tempo","The weather is nice"],["Fa brutto tempo","The weather is bad"],["Piove","It's raining"],["Nevica","It's snowing"],["C'è vento","It's windy"],["C'è il sole","It's sunny"],["È nuvoloso","It's cloudy"],["Che bella giornata!","What a beautiful day!"],["Fa un caldo terribile","It's terribly hot"],["Penso di sì","I think so"],["Penso di no","I don't think so"],["Secondo me hai ragione","I think you're right"],["Non sono d'accordo","I don't agree"],["È una buona idea","It's a good idea"],["Dipende","It depends"],["Forse","Maybe"],["Vedremo","We'll see"]
]},
{cat:"Feelings & states", phrases:[
["Sono felice","I'm happy"],["Sono triste","I'm sad"],["Sono stanco","I'm tired"],["Sono stanca","I'm tired (f)"],["Sono arrabbiato","I'm angry"],["Ho fame","I'm hungry"],["Ho sete","I'm thirsty"],["Ho sonno","I'm sleepy"],["Ho freddo","I'm cold"],["Ho caldo","I'm hot"],["Ho paura","I'm afraid"],["Sono preoccupato","I'm worried"],["Sono emozionato","I'm excited"],["Sono annoiato","I'm bored"],["Mi sento bene","I feel good"],["Mi sento male","I feel bad"],["Sono di fretta","I'm in a hurry"],["Sono pronto","I'm ready"],["Non vedo l'ora","I can't wait"],["Mi manchi","I miss you"]
]},
{cat:"Plans & invitations", phrases:[
["Cosa fai stasera?","What are you doing tonight?"],["Hai programmi?","Do you have plans?"],["Ti va di uscire?","Do you feel like going out?"],["Andiamo a mangiare qualcosa?","Shall we go grab a bite?"],["Vuoi prendere un caffè?","Do you want to get a coffee?"],["Ti va un drink?","How about a drink?"],["Andiamo al cinema?","Shall we go to the cinema?"],["Vieni con noi?","Are you coming with us?"],["Con piacere","With pleasure"],["Volentieri!","Gladly!"],["Mi dispiace, non posso","Sorry, I can't"],["Magari un'altra volta","Maybe another time"],["A che ora ci vediamo?","What time shall we meet?"],["Dove ci incontriamo?","Where shall we meet?"],["Ci vediamo alle otto","See you at eight"],["Va bene per me","Works for me"],["Ti chiamo dopo","I'll call you later"],["Fammi sapere","Let me know"],["Sei libero domani?","Are you free tomorrow?"],["Sarà divertente","It'll be fun"]
]},
{cat:"Phone & messaging", phrases:[
["Pronto?","Hello? (on the phone)"],["Chi parla?","Who's speaking?"],["Posso parlare con Anna?","Can I speak to Anna?"],["Un attimo, prego","One moment, please"],["È occupato","The line is busy"],["Richiamo più tardi","I'll call back later"],["Mi senti?","Can you hear me?"],["Si sente male","The connection is bad"],["Ti richiamo io","I'll call you back"],["Qual è il tuo numero?","What's your number?"],["Ti mando un messaggio","I'll send you a message"],["Ti scrivo dopo","I'll text you later"],["Hai ricevuto il mio messaggio?","Did you get my message?"],["Mandami la posizione","Send me the location"],["Sono senza batteria","My battery is dead"],["Non ho campo","I have no signal"],["Aggiungimi su WhatsApp","Add me on WhatsApp"],["Ci sentiamo","Let's talk soon"],["A più tardi","Until later"],["Ti ho chiamato","I called you"]
]},
{cat:"Likes & preferences", phrases:[
["Mi piace","I like it"],["Non mi piace","I don't like it"],["Mi piace molto","I like it a lot"],["Mi piacciono i gatti","I like cats"],["Adoro la pizza","I love pizza"],["Odio il traffico","I hate traffic"],["Preferisco il tè","I prefer tea"],["Mi interessa","I'm interested"],["Non m'interessa","I'm not interested"],["Che ne pensi?","What do you think?"],["È il mio preferito","It's my favourite"],["Mi piacerebbe","I would like to"],["Vorrei tanto","I'd really like to"],["Non mi va","I don't feel like it"],["Mi fa piacere","It makes me happy"],["Lo trovo bello","I find it nice"],["È fantastico","It's fantastic"],["Non è male","It's not bad"],["Così così","So-so"],["Mi piace di più questo","I like this one more"]
]},
{cat:"Agreement & reactions", phrases:[
["Sì","Yes"],["No","No"],["Certo","Of course"],["Certamente","Certainly"],["Esatto","Exactly"],["Hai ragione","You're right"],["Sono d'accordo","I agree"],["Va bene","Okay"],["D'accordo","Agreed"],["Perfetto","Perfect"],["Ottimo","Great"],["Assolutamente","Absolutely"],["Forse","Maybe"],["Non proprio","Not really"],["Per niente","Not at all"],["Ho capito","I see"],["Davvero?","Really?"],["Incredibile!","Incredible!"],["Che bello!","How nice!"],["Che peccato!","What a pity!"]
]},
{cat:"Numbers in use", phrases:[
["Ne vorrei due","I'd like two of them"],["Solo uno, grazie","Just one, thanks"],["Quanti ne vuoi?","How many do you want?"],["Un po' di più","A little more"],["Un po' di meno","A little less"],["Basta così","That's enough"],["La metà","Half"],["Il doppio","Double"],["Una dozzina","A dozen"],["Un paio","A couple / pair"],["Il primo a sinistra","The first on the left"],["Il secondo piano","The second floor"],["Numero dieci","Number ten"],["Costa venti euro","It costs twenty euros"],["Sono le cinque","It's five o'clock"],["Cento per cento","One hundred percent"],["Tre volte al giorno","Three times a day"],["Per due persone","For two people"],["Più o meno","More or less"],["In totale","In total"]
]},
{cat:"Describing people", phrases:[
["È alto","He's tall"],["È bassa","She's short"],["Ha i capelli biondi","He has blond hair"],["Ha gli occhi azzurri","She has blue eyes"],["È molto simpatico","He's very nice"],["È una persona gentile","She's a kind person"],["Assomiglia a sua madre","He looks like his mother"],["È più grande di me","He's older than me"],["È la mia migliore amica","She's my best friend"],["Sono fratelli","They're brothers"],["Com'è fatto?","What does he look like?"],["Che tipo è?","What's he like?"],["È sposato","He's married"],["È single","She's single"],["Ha due figli","He has two children"],["Quanti anni ha?","How old is he?"],["È un bravo ragazzo","He's a good guy"],["È molto intelligente","She's very smart"],["È un po' timido","He's a bit shy"],["Sono molto simpatici","They're very nice"]
]},
{cat:"Daily routine", phrases:[
["Mi sveglio presto","I wake up early"],["Mi alzo alle sette","I get up at seven"],["Faccio colazione","I have breakfast"],["Vado al lavoro","I go to work"],["Prendo l'autobus","I take the bus"],["Lavoro tutto il giorno","I work all day"],["Pranzo all'una","I have lunch at one"],["Torno a casa","I come home"],["Faccio la spesa","I do the grocery shopping"],["Cucino la cena","I cook dinner"],["Guardo la televisione","I watch TV"],["Leggo un libro","I read a book"],["Mi faccio la doccia","I take a shower"],["Vado a letto tardi","I go to bed late"],["Dormo otto ore","I sleep eight hours"],["Il fine settimana riposo","On weekends I rest"],["Faccio sport","I do sports"],["Incontro gli amici","I meet friends"],["Ogni giorno è uguale","Every day is the same"],["Sono sempre occupato","I'm always busy"]
]},
{cat:"Compliments & encouragement", phrases:[
["Bravo!","Well done!"],["Complimenti!","Congratulations!"],["Che bello!","How beautiful!"],["Ottimo lavoro","Great job"],["Sei bravissimo","You're really good"],["Stai benissimo","You look great"],["Che buono!","How tasty!"],["Mi piace molto","I like it a lot"],["Sono fiero di te","I'm proud of you"],["Continua così","Keep it up"],["Ce la puoi fare","You can do it"],["Non mollare","Don't give up"],["In bocca al lupo!","Good luck!"],["Buona fortuna","Good luck"],["Coraggio!","Come on / be brave!"],["Ben fatto","Well done"],["Sei un genio","You're a genius"],["Hai fatto un ottimo lavoro","You did a great job"],["Che fortuna!","How lucky!"],["Auguri!","Best wishes!"]
]},
{cat:"Apologies & misunderstandings", phrases:[
["Mi dispiace","I'm sorry"],["Mi dispiace tanto","I'm so sorry"],["Scusa il ritardo","Sorry I'm late"],["È colpa mia","It's my fault"],["Non l'ho fatto apposta","I didn't do it on purpose"],["Non volevo offenderti","I didn't mean to offend you"],["Chiedo scusa","I apologize"],["Non importa","It doesn't matter"],["Non ti preoccupare","Don't worry"],["Va tutto bene","It's all fine"],["Nessun problema","No problem"],["È stato un malinteso","It was a misunderstanding"],["Mi sono sbagliato","I was mistaken"],["Hai ragione, scusa","You're right, sorry"],["Posso spiegare?","Can I explain?"],["Non è quello che intendevo","That's not what I meant"],["Perdonami","Forgive me"],["Ti perdono","I forgive you"],["Facciamo pace","Let's make peace"],["Tutto a posto","All good"]
]},
{cat:"Work & study", phrases:[
["Ho una riunione","I have a meeting"],["Sono in ufficio","I'm at the office"],["Lavoro da casa","I work from home"],["Sono in pausa","I'm on a break"],["Ho molto da fare","I have a lot to do"],["Sono molto impegnato","I'm very busy"],["Ti mando un'email","I'll send you an email"],["Qual è la scadenza?","What's the deadline?"],["Ho finito il lavoro","I've finished the work"],["Devo studiare","I have to study"],["Ho un esame domani","I have an exam tomorrow"],["Sto studiando l'italiano","I'm studying Italian"],["Frequento l'università","I attend university"],["Mi sono laureato","I graduated"],["Ho preso un bel voto","I got a good grade"],["Non ho capito la lezione","I didn't understand the lesson"],["Puoi spiegarmelo?","Can you explain it to me?"],["Faccio del mio meglio","I do my best"],["Buon lavoro!","Have a good day at work!"],["Ci vediamo lunedì","See you on Monday"]
]},
{cat:"Useful connectors", phrases:[
["prima di tutto","first of all"],["per esempio","for example"],["in altre parole","in other words"],["per questo","that's why"],["allo stesso tempo","at the same time"],["d'altra parte","on the other hand"],["in ogni caso","in any case"],["soprattutto","above all"],["comunque","anyway"],["inoltre","moreover"],["infatti","in fact"],["tuttavia","nevertheless"],["secondo me","in my opinion"],["a proposito","by the way"],["più o meno","more or less"],["di solito","usually"],["in genere","generally"],["alla fine","in the end"],["così","like this / so"],["quindi","therefore"]
]},
{cat:"Survival expressions", phrases:[
["Non lo so","I don't know"],["Non c'è problema","No problem"],["Va bene così","That's fine"],["Come vuoi","As you wish"],["Dipende","It depends"],["Magari!","I wish!"],["Boh","Dunno"],["Figurati","Don't mention it / no way"],["Dai!","Come on!"],["Andiamo!","Let's go!"],["Aspetta un attimo","Wait a moment"],["Sbrigati!","Hurry up!"],["Stai attento","Be careful"],["Tranquillo","Take it easy"],["Che casino!","What a mess!"],["Che fortuna!","What luck!"],["Meno male","Thank goodness"],["Non fa niente","It doesn't matter"],["Ci penso io","I'll take care of it"],["Vediamo","Let's see"]
]}
];
