/* ============================================================
   IMPARA — additional language packs (French, German,
   Japanese, Korean). Italian lives in data.js (full 2000/500).
   These are curated starter courses on the same engine.
   Card format: [native, english] or [native, english, reading].
   ============================================================ */
const LANG_EXTRA = {};

/* ===================== FRENCH ===================== */
LANG_EXTRA.fr = {
 code:"fr", name:"French", flag:"🇫🇷", tts:"fr-FR", latin:true,
 WORD_THEMES:[
  {cat:"Greetings & basics", words:[["bonjour","hello / good morning"],["bonsoir","good evening"],["salut","hi / bye"],["au revoir","goodbye"],["merci","thank you"],["s'il vous plaît","please"],["oui","yes"],["non","no"],["pardon","excuse me / sorry"],["de rien","you're welcome"],["bienvenue","welcome"],["à bientôt","see you soon"],["s'il te plaît","please (informal)"],["d'accord","okay"],["peut-être","maybe"]]},
  {cat:"People & family", words:[["la famille","the family"],["le père","the father"],["la mère","the mother"],["le frère","the brother"],["la sœur","the sister"],["le fils","the son"],["la fille","the daughter / girl"],["l'enfant","the child"],["l'homme","the man"],["la femme","the woman / wife"],["l'ami","the friend (m)"],["l'amie","the friend (f)"],["le mari","the husband"],["les parents","the parents"],["le bébé","the baby"]]},
  {cat:"Numbers", words:[["un","one"],["deux","two"],["trois","three"],["quatre","four"],["cinq","five"],["six","six"],["sept","seven"],["huit","eight"],["neuf","nine"],["dix","ten"],["vingt","twenty"],["trente","thirty"],["cent","hundred"],["mille","thousand"],["premier","first"]]},
  {cat:"Food & drink", words:[["la nourriture","the food"],["le pain","the bread"],["l'eau","the water"],["le café","the coffee"],["le vin","the wine"],["le fromage","the cheese"],["la viande","the meat"],["le poisson","the fish"],["la pomme","the apple"],["le lait","the milk"],["le repas","the meal"],["le petit-déjeuner","the breakfast"],["le déjeuner","the lunch"],["le dîner","the dinner"],["le dessert","the dessert"]]},
  {cat:"Colours & adjectives", words:[["rouge","red"],["bleu","blue"],["vert","green"],["jaune","yellow"],["noir","black"],["blanc","white"],["grand","big / tall"],["petit","small"],["bon","good"],["mauvais","bad"],["beau","beautiful"],["nouveau","new"],["vieux","old"],["chaud","hot"],["froid","cold"]]},
  {cat:"Time & days", words:[["aujourd'hui","today"],["demain","tomorrow"],["hier","yesterday"],["le matin","the morning"],["le soir","the evening"],["la nuit","the night"],["maintenant","now"],["le jour","the day"],["la semaine","the week"],["le mois","the month"],["l'année","the year"],["lundi","Monday"],["samedi","Saturday"],["dimanche","Sunday"],["l'heure","the hour / time"]]},
  {cat:"Travel & places", words:[["la ville","the city"],["la rue","the street"],["la gare","the station"],["l'hôtel","the hotel"],["le restaurant","the restaurant"],["le magasin","the shop"],["la voiture","the car"],["le train","the train"],["l'avion","the plane"],["la maison","the house"],["la chambre","the room"],["à gauche","to the left"],["à droite","to the right"],["tout droit","straight ahead"],["le billet","the ticket"]]},
  {cat:"Common verbs", words:[["être","to be"],["avoir","to have"],["faire","to do / make"],["aller","to go"],["venir","to come"],["voir","to see"],["savoir","to know"],["pouvoir","to be able"],["vouloir","to want"],["devoir","to have to"],["parler","to speak"],["manger","to eat"],["boire","to drink"],["dormir","to sleep"],["aimer","to like / love"]]},
  {cat:"More verbs", words:[["prendre","to take"],["donner","to give"],["mettre","to put"],["trouver","to find"],["penser","to think"],["dire","to say"],["demander","to ask"],["répondre","to answer"],["acheter","to buy"],["payer","to pay"],["travailler","to work"],["jouer","to play"],["lire","to read"],["écrire","to write"],["écouter","to listen"],["regarder","to watch"],["ouvrir","to open"],["fermer","to close"],["attendre","to wait"],["aider","to help"]]},
  {cat:"Home & objects", words:[["la maison","the house"],["l'appartement","the apartment"],["la cuisine","the kitchen"],["la salle de bain","the bathroom"],["le lit","the bed"],["la table","the table"],["la chaise","the chair"],["la porte","the door"],["la fenêtre","the window"],["la clé","the key"],["le téléphone","the phone"],["l'ordinateur","the computer"],["le livre","the book"],["l'argent","the money"],["le sac","the bag"],["les vêtements","the clothes"],["la chaussure","the shoe"],["le travail","the work"],["l'école","the school"],["le magasin","the shop"]]},
  {cat:"Body & health", words:[["le corps","the body"],["la tête","the head"],["les yeux","the eyes"],["la bouche","the mouth"],["la main","the hand"],["le pied","the foot"],["le cœur","the heart"],["le ventre","the belly"],["malade","sick"],["le médecin","the doctor"],["la douleur","the pain"],["la pharmacie","the pharmacy"],["fatigué","tired"],["le rhume","the cold"],["la fièvre","the fever"],["heureux","happy"],["triste","sad"],["en colère","angry"],["content","glad"],["peur","fear"]]},
  {cat:"Nature & weather", words:[["le soleil","the sun"],["la pluie","the rain"],["la neige","the snow"],["le vent","the wind"],["le ciel","the sky"],["la mer","the sea"],["la montagne","the mountain"],["l'arbre","the tree"],["la fleur","the flower"],["l'eau","the water"],["le feu","the fire"],["la terre","the earth"],["l'animal","the animal"],["le chien","the dog"],["le chat","the cat"],["l'oiseau","the bird"],["le poisson","the fish"],["chaud","hot"],["froid","cold"],["beau","nice (weather)"]]},
 ],
 PHRASE_GROUPS:[
  {cat:"Greetings & politeness", phrases:[["Bonjour !","Hello!"],["Comment allez-vous ?","How are you? (formal)"],["Comment ça va ?","How's it going?"],["Ça va bien, merci","I'm fine, thanks"],["Et vous ?","And you?"],["Enchanté","Nice to meet you"],["Comment vous appelez-vous ?","What's your name?"],["Je m'appelle Paul","My name is Paul"],["Merci beaucoup","Thank you very much"],["Je vous en prie","You're welcome"],["Excusez-moi","Excuse me"],["Bonne journée","Have a nice day"],["À demain","See you tomorrow"],["Au revoir","Goodbye"],["Désolé","Sorry"],["Pas de problème","No problem"]]},
  {cat:"Getting by", phrases:[["Je ne comprends pas","I don't understand"],["Parlez-vous anglais ?","Do you speak English?"],["Pouvez-vous répéter ?","Can you repeat?"],["Plus lentement, s'il vous plaît","More slowly, please"],["Je ne sais pas","I don't know"],["Qu'est-ce que c'est ?","What is it?"],["Comment dit-on… ?","How do you say…?"],["Pouvez-vous m'aider ?","Can you help me?"],["Où sont les toilettes ?","Where is the toilet?"],["Combien ça coûte ?","How much does it cost?"],["Je voudrais…","I would like…"],["C'est combien ?","How much is it?"],["Un instant","One moment"],["Bien sûr","Of course"],["Avec plaisir","With pleasure"],["J'ai besoin d'aide","I need help"]]},
  {cat:"At the restaurant", phrases:[["Une table pour deux","A table for two"],["La carte, s'il vous plaît","The menu, please"],["Qu'est-ce que vous recommandez ?","What do you recommend?"],["Je voudrais commander","I'd like to order"],["Pour moi, le poulet","Chicken for me"],["À boire, de l'eau","To drink, water"],["C'est délicieux","It's delicious"],["L'addition, s'il vous plaît","The bill, please"],["Vous acceptez les cartes ?","Do you take cards?"],["Je suis végétarien","I'm vegetarian"],["Sans glace, merci","No ice, thanks"],["Encore du pain, s'il vous plaît","More bread, please"],["C'était excellent","It was excellent"],["Bon appétit !","Enjoy your meal!"],["Un café, s'il vous plaît","A coffee, please"],["Gardez la monnaie","Keep the change"]]},
  {cat:"Directions & travel", phrases:[["Où est la gare ?","Where is the station?"],["C'est loin ?","Is it far?"],["C'est près d'ici","It's nearby"],["Tournez à gauche","Turn left"],["Tournez à droite","Turn right"],["Continuez tout droit","Keep going straight"],["Je suis perdu","I'm lost"],["Un billet, s'il vous plaît","One ticket, please"],["À quelle heure part le train ?","What time does the train leave?"],["Le train est en retard","The train is late"],["Où puis-je prendre un taxi ?","Where can I get a taxi?"],["Combien de temps ça prend ?","How long does it take?"],["Je voudrais aller à…","I'd like to go to…"],["C'est par où ?","Which way is it?"],["Au prochain feu","At the next traffic light"],["Bon voyage !","Have a good trip!"]]},
  {cat:"Shopping & hotel", phrases:[["Je cherche…","I'm looking for…"],["Je regarde seulement","I'm just looking"],["C'est trop cher","It's too expensive"],["Avez-vous moins cher ?","Do you have anything cheaper?"],["Puis-je l'essayer ?","Can I try it on?"],["Je le prends","I'll take it"],["J'ai une réservation","I have a reservation"],["Une chambre pour une nuit","A room for one night"],["Le petit-déjeuner est inclus ?","Is breakfast included?"],["À quelle heure le départ ?","What time is check-out?"],["La clé, s'il vous plaît","The key, please"],["Le wifi, c'est quoi ?","What's the wifi?"],["Il fait froid dans la chambre","It's cold in the room"],["Pouvez-vous appeler un taxi ?","Can you call a taxi?"],["C'est parfait, merci","It's perfect, thanks"],["Je voudrais payer","I'd like to pay"]]},
  {cat:"Feelings & small talk", phrases:[["Je suis fatigué","I'm tired"],["J'ai faim","I'm hungry"],["J'ai soif","I'm thirsty"],["Je suis content","I'm happy"],["Je ne sais pas","I don't know"],["Je pense que oui","I think so"],["Je suis d'accord","I agree"],["C'est une bonne idée","It's a good idea"],["Ça dépend","It depends"],["Peut-être","Maybe"],["Bien sûr","Of course"],["J'aime ça","I like it"],["Je n'aime pas ça","I don't like it"],["C'est génial","It's great"],["Quel dommage","What a pity"],["Félicitations !","Congratulations!"]]},
  {cat:"Time & plans", phrases:[["Quelle heure est-il ?","What time is it?"],["Il est trois heures","It's three o'clock"],["Quel jour sommes-nous ?","What day is it?"],["Aujourd'hui","Today"],["Demain","Tomorrow"],["La semaine prochaine","Next week"],["Tu es libre ce soir ?","Are you free tonight?"],["On va manger ?","Shall we go eat?"],["Avec plaisir","With pleasure"],["À quelle heure ?","At what time?"],["On se retrouve où ?","Where shall we meet?"],["Je suis en retard","I'm late"],["Dépêche-toi !","Hurry up!"],["Attends-moi","Wait for me"],["Je te rappelle","I'll call you back"],["À tout à l'heure","See you later"]]},
 ],
 grammar:[
  {t:"Gender & articles",b:"Nouns are masculine or feminine. <b>le</b> (m), <b>la</b> (f), <b>l'</b> (before a vowel), <b>les</b> (plural). Indefinite: <b>un</b> (m), <b>une</b> (f), <b>des</b> (plural)."},
  {t:"To be & to have",b:"<b>être</b>: je suis, tu es, il est, nous sommes, vous êtes, ils sont. <b>avoir</b>: j'ai, tu as, il a, nous avons, vous avez, ils ont."},
  {t:"Present tense (-er verbs)",b:"parler → je parle, tu parles, il parle, nous parlons, vous parlez, ils parlent. Most verbs follow this pattern."},
  {t:"Negation",b:"Wrap the verb in <b>ne … pas</b>: <code>Je ne comprends pas</code> (I don't understand)."},
  {t:"Questions",b:"Three ways: intonation (<code>Tu viens ?</code>), <code>est-ce que</code> (<code>Est-ce que tu viens ?</code>), or inversion (<code>Viens-tu ?</code>)."},
  {t:"Polite forms",b:"Use <b>vous</b> with strangers/elders, <b>tu</b> with friends/family. <code>Je voudrais</code> (I would like) is the polite way to ask."},
 ],
 stories:[
  {title:"Au café", level:"A1", lines:[["Bonjour ! Un café, s'il vous plaît.","Hello! A coffee, please."],["Bien sûr. Et avec ça ?","Of course. Anything else?"],["Un croissant aussi.","A croissant too."],["Ça fait trois euros.","That's three euros."],["Merci, bonne journée !","Thank you, have a nice day!"]]},
  {title:"À l'hôtel", level:"A2", lines:[["Bonsoir, j'ai une réservation.","Good evening, I have a reservation."],["À quel nom ?","Under what name?"],["Je m'appelle Marie Dubois.","My name is Marie Dubois."],["Voici la clé, chambre dix.","Here is the key, room ten."],["Le petit-déjeuner est à quelle heure ?","What time is breakfast?"],["De sept heures à dix heures.","From seven to ten."]]},
 ],
 alphabets:null
};

/* ===================== GERMAN ===================== */
LANG_EXTRA.de = {
 code:"de", name:"German", flag:"🇩🇪", tts:"de-DE", latin:true,
 WORD_THEMES:[
  {cat:"Greetings & basics", words:[["hallo","hello"],["guten Morgen","good morning"],["guten Tag","good day"],["guten Abend","good evening"],["tschüss","bye"],["auf Wiedersehen","goodbye"],["danke","thank you"],["bitte","please / you're welcome"],["ja","yes"],["nein","no"],["entschuldigung","excuse me / sorry"],["willkommen","welcome"],["bis bald","see you soon"],["genau","exactly"],["vielleicht","maybe"]]},
  {cat:"People & family", words:[["die Familie","the family"],["der Vater","the father"],["die Mutter","the mother"],["der Bruder","the brother"],["die Schwester","the sister"],["der Sohn","the son"],["die Tochter","the daughter"],["das Kind","the child"],["der Mann","the man / husband"],["die Frau","the woman / wife"],["der Freund","the friend (m)"],["die Freundin","the friend (f)"],["die Eltern","the parents"],["das Baby","the baby"],["der Name","the name"]]},
  {cat:"Numbers", words:[["eins","one"],["zwei","two"],["drei","three"],["vier","four"],["fünf","five"],["sechs","six"],["sieben","seven"],["acht","eight"],["neun","nine"],["zehn","ten"],["zwanzig","twenty"],["dreißig","thirty"],["hundert","hundred"],["tausend","thousand"],["erste","first"]]},
  {cat:"Food & drink", words:[["das Essen","the food"],["das Brot","the bread"],["das Wasser","the water"],["der Kaffee","the coffee"],["der Wein","the wine"],["das Bier","the beer"],["der Käse","the cheese"],["das Fleisch","the meat"],["der Fisch","the fish"],["der Apfel","the apple"],["die Milch","the milk"],["das Frühstück","the breakfast"],["das Mittagessen","the lunch"],["das Abendessen","the dinner"],["der Nachtisch","the dessert"]]},
  {cat:"Colours & adjectives", words:[["rot","red"],["blau","blue"],["grün","green"],["gelb","yellow"],["schwarz","black"],["weiß","white"],["groß","big / tall"],["klein","small"],["gut","good"],["schlecht","bad"],["schön","beautiful"],["neu","new"],["alt","old"],["warm","warm"],["kalt","cold"]]},
  {cat:"Time & days", words:[["heute","today"],["morgen","tomorrow"],["gestern","yesterday"],["der Morgen","the morning"],["der Abend","the evening"],["die Nacht","the night"],["jetzt","now"],["der Tag","the day"],["die Woche","the week"],["der Monat","the month"],["das Jahr","the year"],["Montag","Monday"],["Samstag","Saturday"],["Sonntag","Sunday"],["die Stunde","the hour"]]},
  {cat:"Travel & places", words:[["die Stadt","the city"],["die Straße","the street"],["der Bahnhof","the station"],["das Hotel","the hotel"],["das Restaurant","the restaurant"],["das Geschäft","the shop"],["das Auto","the car"],["der Zug","the train"],["das Flugzeug","the plane"],["das Haus","the house"],["das Zimmer","the room"],["links","left"],["rechts","right"],["geradeaus","straight ahead"],["die Fahrkarte","the ticket"]]},
  {cat:"Common verbs", words:[["sein","to be"],["haben","to have"],["machen","to do / make"],["gehen","to go"],["kommen","to come"],["sehen","to see"],["wissen","to know"],["können","to be able"],["wollen","to want"],["müssen","to have to"],["sprechen","to speak"],["essen","to eat"],["trinken","to drink"],["schlafen","to sleep"],["mögen","to like"]]},
  {cat:"More verbs", words:[["nehmen","to take"],["geben","to give"],["finden","to find"],["denken","to think"],["sagen","to say"],["fragen","to ask"],["antworten","to answer"],["kaufen","to buy"],["bezahlen","to pay"],["arbeiten","to work"],["spielen","to play"],["lesen","to read"],["schreiben","to write"],["hören","to hear"],["schauen","to look"],["öffnen","to open"],["schließen","to close"],["warten","to wait"],["helfen","to help"],["lernen","to learn"]]},
  {cat:"Home & objects", words:[["das Haus","the house"],["die Wohnung","the apartment"],["die Küche","the kitchen"],["das Badezimmer","the bathroom"],["das Bett","the bed"],["der Tisch","the table"],["der Stuhl","the chair"],["die Tür","the door"],["das Fenster","the window"],["der Schlüssel","the key"],["das Telefon","the phone"],["der Computer","the computer"],["das Buch","the book"],["das Geld","the money"],["die Tasche","the bag"],["die Kleidung","the clothes"],["der Schuh","the shoe"],["die Arbeit","the work"],["die Schule","the school"],["das Geschäft","the shop"]]},
  {cat:"Body & health", words:[["der Körper","the body"],["der Kopf","the head"],["die Augen","the eyes"],["der Mund","the mouth"],["die Hand","the hand"],["der Fuß","the foot"],["das Herz","the heart"],["der Bauch","the belly"],["krank","sick"],["der Arzt","the doctor"],["der Schmerz","the pain"],["die Apotheke","the pharmacy"],["müde","tired"],["die Erkältung","the cold"],["das Fieber","the fever"],["glücklich","happy"],["traurig","sad"],["wütend","angry"],["zufrieden","content"],["die Angst","the fear"]]},
  {cat:"Nature & weather", words:[["die Sonne","the sun"],["der Regen","the rain"],["der Schnee","the snow"],["der Wind","the wind"],["der Himmel","the sky"],["das Meer","the sea"],["der Berg","the mountain"],["der Baum","the tree"],["die Blume","the flower"],["das Wasser","the water"],["das Feuer","the fire"],["die Erde","the earth"],["das Tier","the animal"],["der Hund","the dog"],["die Katze","the cat"],["der Vogel","the bird"],["der Fisch","the fish"],["heiß","hot"],["kalt","cold"],["schön","nice"]]},
 ],
 PHRASE_GROUPS:[
  {cat:"Greetings & politeness", phrases:[["Hallo!","Hello!"],["Wie geht es Ihnen?","How are you? (formal)"],["Wie geht's?","How's it going?"],["Gut, danke","Good, thanks"],["Und Ihnen?","And you?"],["Freut mich","Nice to meet you"],["Wie heißen Sie?","What's your name?"],["Ich heiße Anna","My name is Anna"],["Vielen Dank","Thank you very much"],["Gern geschehen","You're welcome"],["Entschuldigung","Excuse me"],["Schönen Tag noch","Have a nice day"],["Bis morgen","See you tomorrow"],["Auf Wiedersehen","Goodbye"],["Es tut mir leid","I'm sorry"],["Kein Problem","No problem"]]},
  {cat:"Getting by", phrases:[["Ich verstehe nicht","I don't understand"],["Sprechen Sie Englisch?","Do you speak English?"],["Können Sie das wiederholen?","Can you repeat that?"],["Langsamer, bitte","Slower, please"],["Ich weiß nicht","I don't know"],["Was ist das?","What is this?"],["Wie sagt man…?","How do you say…?"],["Können Sie mir helfen?","Can you help me?"],["Wo ist die Toilette?","Where is the toilet?"],["Wie viel kostet das?","How much does it cost?"],["Ich möchte…","I would like…"],["Einen Moment, bitte","One moment, please"],["Natürlich","Of course"],["Mit Vergnügen","With pleasure"],["Ich brauche Hilfe","I need help"],["Alles klar","All clear / got it"]]},
  {cat:"At the restaurant", phrases:[["Ein Tisch für zwei","A table for two"],["Die Speisekarte, bitte","The menu, please"],["Was empfehlen Sie?","What do you recommend?"],["Ich möchte bestellen","I'd like to order"],["Für mich das Hähnchen","Chicken for me"],["Zum Trinken Wasser","Water to drink"],["Es ist lecker","It's delicious"],["Die Rechnung, bitte","The bill, please"],["Nehmen Sie Karten?","Do you take cards?"],["Ich bin Vegetarier","I'm vegetarian"],["Ohne Eis, bitte","Without ice, please"],["Noch etwas Brot, bitte","Some more bread, please"],["Es war ausgezeichnet","It was excellent"],["Guten Appetit!","Enjoy your meal!"],["Einen Kaffee, bitte","A coffee, please"],["Stimmt so","Keep the change"]]},
  {cat:"Directions & travel", phrases:[["Wo ist der Bahnhof?","Where is the station?"],["Ist es weit?","Is it far?"],["Es ist in der Nähe","It's nearby"],["Links abbiegen","Turn left"],["Rechts abbiegen","Turn right"],["Geradeaus weiter","Keep going straight"],["Ich habe mich verlaufen","I'm lost"],["Eine Fahrkarte, bitte","One ticket, please"],["Wann fährt der Zug?","When does the train leave?"],["Der Zug hat Verspätung","The train is delayed"],["Wo finde ich ein Taxi?","Where can I find a taxi?"],["Wie lange dauert es?","How long does it take?"],["Ich möchte nach… fahren","I'd like to go to…"],["Welcher Weg ist es?","Which way is it?"],["An der nächsten Ampel","At the next traffic light"],["Gute Reise!","Have a good trip!"]]},
  {cat:"Shopping & hotel", phrases:[["Ich suche…","I'm looking for…"],["Ich schaue nur","I'm just looking"],["Das ist zu teuer","That's too expensive"],["Haben Sie etwas Billigeres?","Do you have anything cheaper?"],["Kann ich es anprobieren?","Can I try it on?"],["Ich nehme es","I'll take it"],["Ich habe eine Reservierung","I have a reservation"],["Ein Zimmer für eine Nacht","A room for one night"],["Ist das Frühstück inklusive?","Is breakfast included?"],["Wann ist der Check-out?","What time is check-out?"],["Den Schlüssel, bitte","The key, please"],["Wie ist das WLAN?","What's the wifi?"],["Im Zimmer ist es kalt","It's cold in the room"],["Können Sie ein Taxi rufen?","Can you call a taxi?"],["Perfekt, danke","Perfect, thanks"],["Ich möchte bezahlen","I'd like to pay"]]},
  {cat:"Feelings & small talk", phrases:[["Ich bin müde","I'm tired"],["Ich habe Hunger","I'm hungry"],["Ich habe Durst","I'm thirsty"],["Ich bin glücklich","I'm happy"],["Ich weiß nicht","I don't know"],["Ich glaube schon","I think so"],["Ich bin einverstanden","I agree"],["Das ist eine gute Idee","That's a good idea"],["Es kommt darauf an","It depends"],["Vielleicht","Maybe"],["Natürlich","Of course"],["Das gefällt mir","I like it"],["Das gefällt mir nicht","I don't like it"],["Das ist toll","That's great"],["Wie schade","What a pity"],["Herzlichen Glückwunsch!","Congratulations!"]]},
  {cat:"Time & plans", phrases:[["Wie spät ist es?","What time is it?"],["Es ist drei Uhr","It's three o'clock"],["Welcher Tag ist heute?","What day is it?"],["Heute","Today"],["Morgen","Tomorrow"],["Nächste Woche","Next week"],["Hast du heute Abend Zeit?","Are you free tonight?"],["Gehen wir essen?","Shall we go eat?"],["Sehr gern","Gladly"],["Um wie viel Uhr?","At what time?"],["Wo treffen wir uns?","Where shall we meet?"],["Ich bin spät dran","I'm late"],["Beeil dich!","Hurry up!"],["Warte auf mich","Wait for me"],["Ich rufe dich zurück","I'll call you back"],["Bis später","See you later"]]},
 ],
 grammar:[
  {t:"Three genders & articles",b:"German has <b>der</b> (m), <b>die</b> (f), <b>das</b> (n), plural <b>die</b>. The article changes with case. Learn each noun with its article!"},
  {t:"To be & to have",b:"<b>sein</b>: ich bin, du bist, er ist, wir sind, ihr seid, sie sind. <b>haben</b>: ich habe, du hast, er hat, wir haben, ihr habt, sie haben."},
  {t:"Present tense",b:"machen → ich mache, du machst, er macht, wir machen, ihr macht, sie machen."},
  {t:"Word order",b:"The verb goes in <b>position 2</b>: <code>Heute gehe ich</code> (Today go I). In questions the verb comes first: <code>Gehst du?</code>"},
  {t:"Cases (intro)",b:"German marks nouns by role: nominative (subject), accusative (object), dative (indirect), genitive (possession). The article shows the case."},
  {t:"Polite Sie",b:"Use capital <b>Sie</b> for formal 'you', <b>du</b> for friends/family, <b>ihr</b> for several friends."},
 ],
 stories:[
  {title:"Im Café", level:"A1", lines:[["Hallo! Einen Kaffee, bitte.","Hello! A coffee, please."],["Natürlich. Sonst noch etwas?","Of course. Anything else?"],["Ja, auch ein Brötchen.","Yes, also a bread roll."],["Das macht drei Euro.","That's three euros."],["Danke, schönen Tag!","Thanks, have a nice day!"]]},
  {title:"Im Hotel", level:"A2", lines:[["Guten Abend, ich habe eine Reservierung.","Good evening, I have a reservation."],["Auf welchen Namen?","Under what name?"],["Ich heiße Thomas Klein.","My name is Thomas Klein."],["Hier ist der Schlüssel, Zimmer acht.","Here is the key, room eight."],["Wann gibt es Frühstück?","When is breakfast?"],["Von sieben bis zehn Uhr.","From seven to ten."]]},
 ],
 alphabets:null
};

/* ===================== JAPANESE ===================== */
LANG_EXTRA.ja = {
 code:"ja", name:"Japanese", flag:"🇯🇵", tts:"ja-JP", latin:false,
 WORD_THEMES:[
  {cat:"Greetings", words:[["こんにちは","hello","konnichiwa"],["おはよう","good morning","ohayō"],["こんばんは","good evening","konbanwa"],["さようなら","goodbye","sayōnara"],["ありがとう","thank you","arigatō"],["すみません","excuse me / sorry","sumimasen"],["はい","yes","hai"],["いいえ","no","iie"],["お願いします","please","onegai shimasu"],["どういたしまして","you're welcome","dōitashimashite"],["はじめまして","nice to meet you","hajimemashite"],["またね","see you","mata ne"]]},
  {cat:"People & family", words:[["家族","family","kazoku"],["父","father","chichi"],["母","mother","haha"],["兄","older brother","ani"],["姉","older sister","ane"],["子供","child","kodomo"],["男の人","man","otoko no hito"],["女の人","woman","onna no hito"],["友達","friend","tomodachi"],["先生","teacher","sensei"],["私","I / me","watashi"],["あなた","you","anata"]]},
  {cat:"Numbers", words:[["一","one","ichi"],["二","two","ni"],["三","three","san"],["四","four","yon / shi"],["五","five","go"],["六","six","roku"],["七","seven","nana / shichi"],["八","eight","hachi"],["九","nine","kyū"],["十","ten","jū"],["百","hundred","hyaku"],["千","thousand","sen"]]},
  {cat:"Food & drink", words:[["食べ物","food","tabemono"],["水","water","mizu"],["お茶","tea","ocha"],["コーヒー","coffee","kōhī"],["ご飯","rice / meal","gohan"],["パン","bread","pan"],["肉","meat","niku"],["魚","fish","sakana"],["りんご","apple","ringo"],["牛乳","milk","gyūnyū"],["朝ご飯","breakfast","asagohan"],["晩ご飯","dinner","bangohan"]]},
  {cat:"Everyday words", words:[["家","house","ie"],["学校","school","gakkō"],["車","car","kuruma"],["電車","train","densha"],["店","shop","mise"],["町","town","machi"],["今日","today","kyō"],["明日","tomorrow","ashita"],["昨日","yesterday","kinō"],["今","now","ima"],["時間","time","jikan"],["お金","money","okane"]]},
  {cat:"Verbs & adjectives", words:[["食べる","to eat","taberu"],["飲む","to drink","nomu"],["行く","to go","iku"],["来る","to come","kuru"],["見る","to see","miru"],["する","to do","suru"],["話す","to speak","hanasu"],["大きい","big","ōkii"],["小さい","small","chiisai"],["いい","good","ii"],["暑い","hot","atsui"],["寒い","cold","samui"]]},
  {cat:"Time & days", words:[["朝","morning","asa"],["昼","noon / daytime","hiru"],["夜","night","yoru"],["分","minute","fun"],["週末","weekend","shūmatsu"],["月曜日","Monday","getsuyōbi"],["火曜日","Tuesday","kayōbi"],["土曜日","Saturday","doyōbi"],["日曜日","Sunday","nichiyōbi"],["毎日","every day","mainichi"],["来年","next year","rainen"],["去年","last year","kyonen"]]},
  {cat:"Places & directions", words:[["駅","station","eki"],["空港","airport","kūkō"],["ホテル","hotel","hoteru"],["レストラン","restaurant","resutoran"],["病院","hospital","byōin"],["銀行","bank","ginkō"],["トイレ","toilet","toire"],["右","right","migi"],["左","left","hidari"],["まっすぐ","straight","massugu"],["ここ","here","koko"],["そこ","there","soko"]]},
 ],
 PHRASE_GROUPS:[
  {cat:"Greetings & politeness", phrases:[["こんにちは","Hello","konnichiwa"],["お元気 ですか","How are you?","ogenki desu ka"],["元気 です","I'm fine","genki desu"],["ありがとう ございます","Thank you","arigatō gozaimasu"],["どう いたしまして","You're welcome","dōitashimashite"],["すみません","Excuse me","sumimasen"],["お名前 は 何 ですか","What's your name?","onamae wa nan desu ka"],["私 は アンナ です","I am Anna","watashi wa Anna desu"],["はじめまして","Nice to meet you","hajimemashite"],["さようなら","Goodbye","sayōnara"],["また 明日","See you tomorrow","mata ashita"],["ごめんなさい","I'm sorry","gomen nasai"]]},
  {cat:"Getting by", phrases:[["わかりません","I don't understand","wakarimasen"],["英語 を 話せますか","Do you speak English?","eigo o hanasemasu ka"],["もう一度 お願いします","Once more, please","mō ichido onegai shimasu"],["ゆっくり お願いします","Slowly, please","yukkuri onegai shimasu"],["わかりません","I don't know","wakarimasen"],["これ は 何 ですか","What is this?","kore wa nan desu ka"],["助けて ください","Please help me","tasukete kudasai"],["トイレ は どこ ですか","Where is the toilet?","toire wa doko desu ka"],["いくら ですか","How much is it?","ikura desu ka"],["これ を ください","This one, please","kore o kudasai"],["ちょっと 待って ください","Wait a moment please","chotto matte kudasai"],["大丈夫 です","It's okay","daijōbu desu"]]},
  {cat:"Restaurant & shopping", phrases:[["メニュー を ください","The menu, please","menyū o kudasai"],["おすすめ は 何 ですか","What do you recommend?","osusume wa nan desu ka"],["水 を ください","Water, please","mizu o kudasai"],["おいしい です","It's delicious","oishii desu"],["お会計 お願いします","The bill, please","okaikei onegai shimasu"],["カード は 使えますか","Can I use a card?","kādo wa tsukaemasu ka"],["これ を 探して います","I'm looking for this","kore o sagashite imasu"],["高い です","It's expensive","takai desu"],["これ に します","I'll take this","kore ni shimasu"],["いただきます","Let's eat (before a meal)","itadakimasu"],["ごちそうさま","Thanks for the meal","gochisōsama"],["コーヒー を 一つ","One coffee","kōhī o hitotsu"]]},
  {cat:"Travel & directions", phrases:[["駅 は どこ ですか","Where is the station?","eki wa doko desu ka"],["遠い ですか","Is it far?","tōi desu ka"],["近い です","It's near","chikai desu"],["左 です","It's on the left","hidari desu"],["右 です","It's on the right","migi desu"],["まっすぐ です","Straight ahead","massugu desu"],["道 に 迷いました","I'm lost","michi ni mayoimashita"],["切符 を ください","A ticket, please","kippu o kudasai"],["電車 は 何時 ですか","What time is the train?","densha wa nanji desu ka"],["タクシー を お願いします","A taxi, please","takushī o onegai shimasu"],["…へ 行きたい です","I want to go to…","… e ikitai desu"],["気を つけて","Take care","ki o tsukete"]]},
  {cat:"Feelings & small talk", phrases:[["疲れました","I'm tired","tsukaremashita"],["お腹 が すきました","I'm hungry","onaka ga sukimashita"],["のど が かわきました","I'm thirsty","nodo ga kawakimashita"],["嬉しい です","I'm happy","ureshii desu"],["楽しい です","It's fun","tanoshii desu"],["そう です ね","That's right","sō desu ne"],["いい です ね","Sounds good","ii desu ne"],["本当 ですか","Really?","hontō desu ka"],["もちろん","Of course","mochiron"],["たぶん","Maybe","tabun"],["がんばって","Hang in there","ganbatte"],["おめでとう","Congratulations","omedetō"]]},
 ],
 grammar:[
  {t:"Three scripts",b:"Japanese mixes <b>hiragana</b> (ひらがな, for grammar & native words), <b>katakana</b> (カタカナ, for foreign words), and <b>kanji</b> (漢字, Chinese characters for meaning). See the Alphabet charts in this tab."},
  {t:"Word order (SOV)",b:"The verb comes <b>last</b>: <code>私は寿司を食べる</code> = I + sushi + eat (I eat sushi)."},
  {t:"Particles",b:"Little markers show a word's role: <b>は (wa)</b> topic, <b>を (o)</b> object, <b>が (ga)</b> subject, <b>に (ni)</b> to/at, <b>の (no)</b> possessive (like 's)."},
  {t:"です / ます (polite)",b:"<b>です (desu)</b> ≈ 'is' for polite statements: <code>元気です</code> (I'm fine). Verbs in <b>～ます</b> form are the polite present: <code>食べます</code> (I eat)."},
  {t:"Questions with か",b:"Add <b>か (ka)</b> to the end to make a question: <code>元気ですか？</code> (Are you well?)."},
  {t:"Counting",b:"Numbers often need counters (本 for long things, 枚 for flat, つ for general). Start with the general one: 一つ, 二つ, 三つ (hitotsu, futatsu, mittsu)."},
 ],
 stories:[
  {title:"カフェで (At the café)", level:"A1", lines:[["こんにちは。コーヒー を ください。","Hello. A coffee, please."],["はい。ほか に は？","Yes. Anything else?"],["パン も お願いします。","Bread too, please."],["三百円 です。","That's 300 yen."],["ありがとう ございます。","Thank you."]]},
  {title:"じこしょうかい (Introduction)", level:"A1", lines:[["はじめまして。","Nice to meet you."],["私 は ケン です。","I am Ken."],["学生 です。","I'm a student."],["どうぞ よろしく。","Pleased to meet you."]]},
 ],
 alphabets:[
  {name:"Hiragana ひらがな", chars:[["a","あ"],["i","い"],["u","う"],["e","え"],["o","お"],["ka","か"],["ki","き"],["ku","く"],["ke","け"],["ko","こ"],["sa","さ"],["shi","し"],["su","す"],["se","せ"],["so","そ"],["ta","た"],["chi","ち"],["tsu","つ"],["te","て"],["to","と"],["na","な"],["ni","に"],["nu","ぬ"],["ne","ね"],["no","の"],["ha","は"],["hi","ひ"],["fu","ふ"],["he","へ"],["ho","ほ"],["ma","ま"],["mi","み"],["mu","む"],["me","め"],["mo","も"],["ya","や"],["yu","ゆ"],["yo","よ"],["ra","ら"],["ri","り"],["ru","る"],["re","れ"],["ro","ろ"],["wa","わ"],["wo","を"],["n","ん"]]},
  {name:"Katakana カタカナ", chars:[["a","ア"],["i","イ"],["u","ウ"],["e","エ"],["o","オ"],["ka","カ"],["ki","キ"],["ku","ク"],["ke","ケ"],["ko","コ"],["sa","サ"],["shi","シ"],["su","ス"],["se","セ"],["so","ソ"],["ta","タ"],["chi","チ"],["tsu","ツ"],["te","テ"],["to","ト"],["na","ナ"],["ni","ニ"],["nu","ヌ"],["ne","ネ"],["no","ノ"],["ha","ハ"],["hi","ヒ"],["fu","フ"],["he","ヘ"],["ho","ホ"],["ma","マ"],["mi","ミ"],["mu","ム"],["me","メ"],["mo","モ"],["ya","ヤ"],["yu","ユ"],["yo","ヨ"],["ra","ラ"],["ri","リ"],["ru","ル"],["re","レ"],["ro","ロ"],["wa","ワ"],["wo","ヲ"],["n","ン"]]}
 ]
};

/* ===================== KOREAN ===================== */
LANG_EXTRA.ko = {
 code:"ko", name:"Korean", flag:"🇰🇷", tts:"ko-KR", latin:false,
 WORD_THEMES:[
  {cat:"Greetings", words:[["안녕하세요","hello","annyeonghaseyo"],["안녕","hi / bye (casual)","annyeong"],["안녕히 가세요","goodbye (to one leaving)","annyeonghi gaseyo"],["감사합니다","thank you","gamsahamnida"],["고맙습니다","thank you","gomapseumnida"],["죄송합니다","I'm sorry","joesonghamnida"],["네","yes","ne"],["아니요","no","aniyo"],["실례합니다","excuse me","sillyehamnida"],["천만에요","you're welcome","cheonmaneyo"],["반갑습니다","nice to meet you","bangapseumnida"],["또 봐요","see you","tto bwayo"]]},
  {cat:"People & family", words:[["가족","family","gajok"],["아버지","father","abeoji"],["어머니","mother","eomeoni"],["형","older brother (m)","hyeong"],["누나","older sister (m)","nuna"],["아이","child","ai"],["남자","man","namja"],["여자","woman","yeoja"],["친구","friend","chingu"],["선생님","teacher","seonsaengnim"],["저","I / me (polite)","jeo"],["당신","you","dangsin"]]},
  {cat:"Numbers", words:[["하나","one","hana"],["둘","two","dul"],["셋","three","set"],["넷","four","net"],["다섯","five","daseot"],["여섯","six","yeoseot"],["일곱","seven","ilgop"],["여덟","eight","yeodeol"],["아홉","nine","ahop"],["열","ten","yeol"],["백","hundred","baek"],["천","thousand","cheon"]]},
  {cat:"Food & drink", words:[["음식","food","eumsik"],["물","water","mul"],["차","tea","cha"],["커피","coffee","keopi"],["밥","rice / meal","bap"],["빵","bread","ppang"],["고기","meat","gogi"],["생선","fish","saengseon"],["사과","apple","sagwa"],["우유","milk","uyu"],["김치","kimchi","gimchi"],["아침","breakfast / morning","achim"]]},
  {cat:"Everyday words", words:[["집","house","jip"],["학교","school","hakgyo"],["차","car","cha"],["기차","train","gicha"],["가게","shop","gage"],["도시","city","dosi"],["오늘","today","oneul"],["내일","tomorrow","naeil"],["어제","yesterday","eoje"],["지금","now","jigeum"],["시간","time","sigan"],["돈","money","don"]]},
  {cat:"Verbs & adjectives", words:[["먹다","to eat","meokda"],["마시다","to drink","masida"],["가다","to go","gada"],["오다","to come","oda"],["보다","to see","boda"],["하다","to do","hada"],["말하다","to speak","malhada"],["크다","big","keuda"],["작다","small","jakda"],["좋다","good","jota"],["덥다","hot","deopda"],["춥다","cold","chupda"]]},
  {cat:"Time & days", words:[["점심","lunch / noon","jeomsim"],["저녁","evening / dinner","jeonyeok"],["밤","night","bam"],["분","minute","bun"],["시","o'clock / hour","si"],["주말","weekend","jumal"],["월요일","Monday","woryoil"],["토요일","Saturday","toyoil"],["일요일","Sunday","iryoil"],["매일","every day","maeil"],["작년","last year","jangnyeon"],["내년","next year","naenyeon"]]},
  {cat:"Places & directions", words:[["역","station","yeok"],["공항","airport","gonghang"],["호텔","hotel","hotel"],["식당","restaurant","sikdang"],["병원","hospital","byeongwon"],["은행","bank","eunhaeng"],["화장실","toilet","hwajangsil"],["오른쪽","right","oreunjjok"],["왼쪽","left","oenjjok"],["여기","here","yeogi"],["거기","there","geogi"],["똑바로","straight","ttokbaro"]]},
 ],
 PHRASE_GROUPS:[
  {cat:"Greetings & politeness", phrases:[["안녕하세요","Hello","annyeonghaseyo"],["잘 지내세요?","How are you?","jal jinaeseyo"],["잘 지내요","I'm fine","jal jinaeyo"],["감사합니다","Thank you","gamsahamnida"],["천만에요","You're welcome","cheonmaneyo"],["실례합니다","Excuse me","sillyehamnida"],["이름이 뭐예요?","What's your name?","ireumi mwoyeyo"],["저는 안나예요","I am Anna","jeoneun Anna-yeyo"],["반갑습니다","Nice to meet you","bangapseumnida"],["안녕히 계세요","Goodbye (staying)","annyeonghi gyeseyo"],["내일 봐요","See you tomorrow","naeil bwayo"],["죄송합니다","I'm sorry","joesonghamnida"]]},
  {cat:"Getting by", phrases:[["모르겠어요","I don't understand","moreugesseoyo"],["영어 할 수 있어요?","Can you speak English?","yeongeo hal su isseoyo"],["다시 말해 주세요","Please say it again","dasi malhae juseyo"],["천천히 말해 주세요","Please speak slowly","cheoncheonhi malhae juseyo"],["몰라요","I don't know","mollayo"],["이게 뭐예요?","What is this?","ige mwoyeyo"],["도와주세요","Please help me","dowajuseyo"],["화장실이 어디예요?","Where is the toilet?","hwajangsiri eodiyeyo"],["얼마예요?","How much is it?","eolmayeyo"],["이거 주세요","This one, please","igeo juseyo"],["잠깐만요","Just a moment","jamkkanmanyo"],["괜찮아요","It's okay","gwaenchanayo"]]},
  {cat:"Restaurant & shopping", phrases:[["메뉴 주세요","The menu, please","menyu juseyo"],["뭐가 맛있어요?","What is tasty?","mwoga masisseoyo"],["물 주세요","Water, please","mul juseyo"],["맛있어요","It's delicious","masisseoyo"],["계산서 주세요","The bill, please","gyesanseo juseyo"],["카드 돼요?","Can I pay by card?","kadeu dwaeyo"],["이거 찾고 있어요","I'm looking for this","igeo chatgo isseoyo"],["비싸요","It's expensive","bissayo"],["이걸로 할게요","I'll take this","igeollo halgeyo"],["잘 먹겠습니다","I'll enjoy the meal","jal meokgesseumnida"],["잘 먹었습니다","Thanks for the meal","jal meogeosseumnida"],["커피 한 잔","One coffee","keopi han jan"]]},
  {cat:"Travel & directions", phrases:[["역이 어디예요?","Where is the station?","yeogi eodiyeyo"],["멀어요?","Is it far?","meoreoyo"],["가까워요","It's near","gakkawoyo"],["왼쪽이에요","It's on the left","oenjjogieyo"],["오른쪽이에요","It's on the right","oreunjjogieyo"],["똑바로 가세요","Go straight","ttokbaro gaseyo"],["길을 잃었어요","I'm lost","gireul ireosseoyo"],["표 주세요","A ticket, please","pyo juseyo"],["기차가 몇 시예요?","What time is the train?","gichaga myeot siyeyo"],["택시를 불러 주세요","Please call a taxi","taeksireul bulleo juseyo"],["…에 가고 싶어요","I want to go to…","…e gago sipeoyo"],["조심하세요","Be careful","josimhaseyo"]]},
  {cat:"Feelings & small talk", phrases:[["피곤해요","I'm tired","pigonhaeyo"],["배고파요","I'm hungry","baegopayo"],["목말라요","I'm thirsty","mongmallayo"],["행복해요","I'm happy","haengbokhaeyo"],["재미있어요","It's fun","jaemiisseoyo"],["맞아요","That's right","majayo"],["좋아요","Good / I like it","joayo"],["정말요?","Really?","jeongmaryo"],["물론이죠","Of course","mullonijyo"],["아마도","Maybe","amado"],["화이팅","Good luck (fighting!)","hwaiting"],["축하해요","Congratulations","chukahaeyo"]]},
 ],
 grammar:[
  {t:"Hangul — a smart alphabet",b:"Korean uses <b>한글 (Hangul)</b>, an alphabet of ~24 letters grouped into syllable blocks (e.g., ㅎ+ㅏ+ㄴ → 한). It's phonetic and learnable in days. See the Alphabet chart in this tab."},
  {t:"Word order (SOV)",b:"The verb comes <b>last</b>: <code>저는 밥을 먹어요</code> = I + rice + eat (I eat rice)."},
  {t:"Particles",b:"Markers show roles: <b>은/는</b> topic, <b>이/가</b> subject, <b>을/를</b> object, <b>에</b> to/at, <b>의</b> possessive."},
  {t:"Politeness levels",b:"Endings set formality. The friendly-polite <b>～요</b> ending (있어요, 가요) works in most situations. <b>～습니다/ㅂ니다</b> is more formal."},
  {t:"No articles, no gender",b:"There's no a/the and no grammatical gender — a relief! Context and particles carry the meaning."},
  {t:"Two number systems",b:"Native Korean (하나, 둘, 셋…) for counting things & age; Sino-Korean (일, 이, 삼…) for dates, money, phone numbers."},
 ],
 stories:[
  {title:"카페에서 (At the café)", level:"A1", lines:[["안녕하세요. 커피 주세요.","Hello. A coffee, please."],["네. 더 필요하세요?","Yes. Anything else?"],["빵도 주세요.","Bread too, please."],["삼천 원이에요.","That's 3,000 won."],["감사합니다.","Thank you."]]},
  {title:"자기소개 (Introduction)", level:"A1", lines:[["안녕하세요.","Hello."],["저는 민수예요.","I am Minsu."],["학생이에요.","I'm a student."],["만나서 반갑습니다.","Nice to meet you."]]},
 ],
 alphabets:[
  {name:"Hangul consonants 자음", chars:[["g/k","ㄱ"],["n","ㄴ"],["d/t","ㄷ"],["r/l","ㄹ"],["m","ㅁ"],["b/p","ㅂ"],["s","ㅅ"],["ng/—","ㅇ"],["j","ㅈ"],["ch","ㅊ"],["k","ㅋ"],["t","ㅌ"],["p","ㅍ"],["h","ㅎ"]]},
  {name:"Hangul vowels 모음", chars:[["a","ㅏ"],["ya","ㅑ"],["eo","ㅓ"],["yeo","ㅕ"],["o","ㅗ"],["yo","ㅛ"],["u","ㅜ"],["yu","ㅠ"],["eu","ㅡ"],["i","ㅣ"],["ae","ㅐ"],["e","ㅔ"]]}
 ]
};

/* ===================== HIGH VALYRIAN (bonus pack) ===================== */
/* A constructed language from Game of Thrones. No native TTS exists,
   so audio uses an English voice — pronunciation is approximate. */
LANG_EXTRA.hv = {
 code:"hv", name:"High Valyrian", flag:"🐉", tts:"en-US", latin:true,
 WORD_THEMES:[
  {cat:"Greetings & basics", words:[["rytsas","hello"],["kirimvose","thank you"],["biarvose","you're welcome"],["geros ilas","goodbye"],["kostilus","please"],["kessa","yes"],["daor","no / not"],["issa","is"],["se","and"],["sīr","now / already"],["sȳz","good"],["mittys","fool"]]},
  {cat:"Pronouns", words:[["nyke","I"],["ao","you"],["ziry","he / she / it"],["īlon","we"],["jeme","you (plural)"],["pōnta","they"],["ñuha","my"],["ñuhon","mine"],["aōhon","yours"],["zȳhon","his / hers"],["īlvon","ours"],["pōjon","theirs"]]},
  {cat:"Question words", words:[["sparos","who"],["skoros","what"],["skorī","when"],["skoriot","where"],["skoro syt","why"],["skorkydoso","how"],["skorverdon","how many"]]},
  {cat:"People & family", words:[["vala","man"],["ābra","woman"],["riñus","girl"],["taoba","boy"],["kepa","father"],["muña","mother"],["lēkia","older brother"],["valonqar","younger brother"],["hāedar","younger sister"],["mandia","older sister"],["dārys","king"],["dāria","queen"],["trēsys","son"],["azantys","knight"],["raqiros","friend"]]},
  {cat:"Animals & nature", words:[["zaldrīzes","dragon"],["anne","horse"],["kēli","cat"],["hontes","bird"],["qintir","turtle"],["turgon","worm"],["hūra","moon"],["vēzos","sun"],["embar","sea"],["tegon","earth"],["blēnos","mountain"],["jelmāzma","storm"],["perzys","fire"]]},
  {cat:"Numbers", words:[["mēre","one"],["lanta","two"],["hāre","three"],["izula","four"],["tōma","five"],["bȳre","six"],["sīkuda","seven"],["jēnqa","eight"],["vōre","nine"],["ampa","ten"],["lantēpsa","twenty"],["hārēpsa","thirty"],["tōmēpsa","fifty"],["gār","hundred"],["pyrys","thousand"]]},
  {cat:"Colours", words:[["timpa","white / light"],["zōbrie","black / dark"],["qeldlie","yellow / orange"],["mele","red"],["kasta","blue / green"]]},
  {cat:"Verbs I", words:[["urnegon","to see"],["rȳbagon","to hear"],["jorrāelagon","to love"],["ȳdragon","to speak"],["nevegon","to carry"],["bardugon","to write"],["kostagon","to be able"],["sylugon","to try"],["gīmigon","to know"],["ipradagon","to eat"],["keligon","to stop"],["brōzagon","to name"]]},
  {cat:"Verbs II", words:[["kisikagon","to feed"],["mijegon","to lack"],["enkagon","to owe"],["idakogon","to attack"],["morghūljagon","to die"],["dohaeragon","to serve"],["gaomagon","to do"],["ilagon","to lie down"],["jomīsagon","to wear"],["sahagon","to make / cause"]]},
  {cat:"Objects & food", words:[["havon","bread"],["averilla","wine"],["avero","grape"],["rōbir","fig"],["onjapos","carrot"],["krēgo","beet"],["qurdon","table"],["belmos","chain"],["gelte","helmet"],["zāeres","crystal"],["lōgor","boat"],["kisalbar","feast"],["brōzi","name"],["ēngos","tongue / language"],["tubis","day"],["dracarys","dragonfire"]]},
  {cat:"Adjectives & more", words:[["ēngenka","tasty"],["udrimmi","witty"],["zaldrīzerme","indestructible"],["averilloma","drunk"],["kony","that"],["kesy","this"],["bisy","this (animate)"],["bony","that (animate)"],["tolmīhy","stranger"],["kostio","hero"],["jentys","leader"],["buzdari","enslaved"]]},
 ],
 PHRASE_GROUPS:[
  {cat:"Famous lines", phrases:[["Valar morghulis","All men must die"],["Valar dohaeris","All men must serve"],["Dracarys","Dragonfire — burn!"],["Zaldrīzes buzdari iksos daor","A dragon is not a slave"],["Avy jorrāelan","I love you"],["Kirimvose","Thank you"],["Biarvose","You're welcome"],["Rytsas","Hello"],["Geros ilas","Goodbye"],["Kostilus","Please"]]},
  {cat:"Useful basics", phrases:[["Kessa","Yes"],["Daor","No"],["Daenerys iksan","I am Daenerys"],["Skoros issa?","What is it?"],["Sparos ao?","Who are you?"],["Skoriot?","Where?"],["Ñuha raqiros","My friend"],["Ñuha dāria","My queen"],["Ñuha dārys","My king"],["Ñuha muña","My mother"],["Rȳban","I hear"],["Ūndan","I saw"],["Iprattan","I have eaten"],["Jorrāelan","I love"],["Dohaeran","I serve"],["Mēre, lanta, hāre","One, two, three"]]},
 ],
 grammar:[
  {t:"What is High Valyrian?",b:"A constructed language created by David J. Peterson for <i>Game of Thrones</i>. Unlike Italian or French, the language has only a few hundred <b>documented</b> words in total — so this course covers the real attested vocabulary (greetings, family, numbers, dragons, verbs, colours, famous lines) rather than an invented 2,000-word list. It's the honest full extent of the known language."},
  {t:"Famous phrases",b:"<b>Valar morghulis</b> — all men must die · <b>Valar dohaeris</b> — all men must serve · <b>Dracarys</b> — dragonfire (the command to breathe fire)."},
  {t:"A complex grammar",b:"High Valyrian has <b>4 genders</b> (lunar, solar, terrestrial, aquatic), <b>8 noun cases</b>, and rich verb conjugation — far more inflected than English. Treat this pack as fun exposure, not mastery."},
  {t:"Pronunciation note",b:"No text-to-speech voice exists for High Valyrian, so the 🔊 button uses an English voice and is only a rough approximation. <code>ā</code>, <code>ē</code>, <code>ī</code>, <code>ō</code>, <code>ū</code> are long vowels."},
 ],
 stories:[
  {title:"Daor zaldrīzes", level:"Fun", lines:[["Zaldrīzes buzdari iksos daor.","A dragon is not a slave."],["Valar morghulis.","All men must die."],["Valar dohaeris.","All men must serve."],["Dracarys!","Dragonfire — burn!"]]},
 ],
 alphabets:null
};
